/* ELPA21 goal bank — for the LSP Builder.

   Four domains × five levels × four goals. Each goal is tied to one of the ten
   ELP Standards (std) and written to be measured: a behavior, the condition it
   happens under, and how progress is shown (ev). The level descriptions follow
   the ELPA21 achievement levels: 1 words and phrases with support · 2 short
   sentences on familiar topics · 3 expanded sentences, errors do not impede ·
   4 grade-appropriate with support · 5 independent, minimal errors.

   Edit freely. Keep each goal one sentence; keep "by the spring ELPT" or a
   date in it so it stays a target and not a wish.

   Evidence (ev) is written to be realistic for a teacher with a full load:
   it names the instrument, how often (mostly every other week, monthly or
   per nine weeks — weekly only for one-minute probes), where it is kept
   (folder, tracker, recording), and what counts as progress from a
   baseline. Wherever possible it uses something that already exists — the
   department rubric, the content teacher's own quiz, a phone voice memo —
   rather than a new assessment.

   ELP Standards: 1 construct meaning · 2 participate in exchanges · 3 speak
   and write about texts · 4 claims with evidence · 5 research · 6 analyze
   arguments · 7 adapt language to audience · 8 word meaning · 9 clear and
   coherent speech/text · 10 standard English. */
window.ELPA21_GOALS = {
L: {
 1: [
  {std:1, g:"Follow one- and two-step classroom directions given with gestures or a model, correctly in 4 of 5 checks by the spring ELPT.", ev:"Once a week during a normal lesson, the EL teacher gives five one- or two-step directions and tallies correct/incorrect on a sticky note in the student folder. Baseline the first week; progress is the tally moving from 2/5 toward 4/5 by the nine-weeks review.", who:"EL teacher: model each direction with a gesture, then fade the gesture (Move 5, check without asking 'Do you understand?'). Content teachers: give directions one step at a time and point to the materials. Para: sit near, repeat the step quietly."},
  {std:1, g:"Point to or pick the picture that matches a word or short phrase the teacher says, in 8 of 10 trials by January.", ev:"Ten picture cards from the week's vocabulary, teacher says the word, student points; scored every other week, two minutes, recorded as x/10 on the First 100 Words tracker. Progress is three checks in a row at 8/10 or better.", who:"EL teacher: 10 minutes a day on First 100 Words with tap-to-hear, picture first. Content teachers: post three picture-labeled words per lesson (Move 2, preview three words). Family: the printable flashcards go home."},
  {std:8, g:"Show understanding of 50 high-frequency school words heard in context (schedule, materials, routines) by responding correctly 80% of the time.", ev:"The First 100 Words tracker, marked once a month: the teacher reads 20 words in a sentence each and the student shows meaning (points, acts, picks). Progress is the running total of words mastered, graphed on the tracker.", who:"EL teacher: First 100 Words groups in order, one group a week, quiz modes on Friday. Office and content teachers: use the same school words the student is learning (schedule, materials, routines). Para: label the student's materials."},
  {std:2, g:"Respond to yes/no and either/or questions about a lesson with a gesture, word or short phrase in 4 of 5 opportunities.", ev:"During one lesson a week the EL teacher asks five yes/no or either/or questions and tallies responses. Keep the five slips per nine weeks; progress is the ratio rising and the responses moving from gestures to words.", who:"EL teacher: ask the student first in every lesson with an either/or question (Move 3 frames posted). Content teachers: a yes/no check-in at the door and once mid-lesson. Partner: a bilingual peer seated beside the student."},
 ],
 2: [
  {std:1, g:"Identify the topic and one key detail of a short teacher explanation on a familiar subject, with visual support, in 4 of 5 checks by the spring ELPT.", ev:"A two-question exit ticket after one mini-lesson a week — 'What was it about?' and 'Tell one thing you heard' — answered in words or a drawing. File the tickets; progress is correct topic in 4 of the last 5 tickets.", who:"EL teacher: teach 'the topic was ___' and 'I heard ___' as frames, practice on 3-minute clips. Content teachers: say the topic twice and write it on the board (Move 1, post and say the language goal). Co-teacher: sits with the student during the mini-lesson."},
  {std:1, g:"Follow multi-step oral directions for a classroom task without a model, correctly in 4 of 5 checks by March.", ev:"Every other week, a three-step task without a model ('get your notebook, write the date, underline the title'), scored right/wrong on a dated checklist. Progress is four consecutive correct checks.", who:"EL teacher: multi-step direction games with real materials, build to three steps. Content teachers: number the steps on the board and point as you say them. Para: ask the student to repeat the steps back before starting."},
  {std:2, g:"Understand and answer simple wh- questions (who, what, where, when) about a lesson or a classmate's statement in 4 of 5 opportunities.", ev:"Once a week the teacher sits in on partner talk for two minutes and scores wh- question responses 0 (no response), 1 (partly right), 2 (right) on a clipboard sheet. Progress is the average moving above 1.5 for a month.", who:"EL teacher: wh- question card on the desk; daily partner talk with wh- frames (Move 19, structure the partner talk). Content teachers: ask the student one wh- question per class, wait time 5 seconds (Move 5). Peer: a trained partner for turn-and-talk."},
  {std:8, g:"Recognize 100 academic and content words when heard in a sentence, scoring 80% on a listening vocabulary check by January.", ev:"A 20-item listening vocabulary check once a month, built from that month's content words: teacher reads a sentence, student picks the picture or definition. Recorded as a percentage; progress is 60% → 80% across the semester.", who:"EL teacher: content words previewed Monday with pictures and cognates (Moves 2 and 10). Content teachers: word wall with images, pointed at when the word is said (Move 11). Family: a bilingual glossary of the month's words sent home."},
 ],
 3: [
  {std:1, g:"Identify the main idea and two supporting details of a grade-level read-aloud or short video on a familiar academic topic, without visual support, in 4 of 5 checks.", ev:"Every other week, a main-idea-and-two-details organizer completed after a grade-level read-aloud or a 5-minute video, scored 0–3 against the teacher's key. Progress is a 3 in three of the last four.", who:"EL teacher: teach the main-idea organizer on short videos, think aloud first (Move 16, read aloud, think aloud). Content teachers: pause twice per read-aloud to ask 'what is this part about?'. Co-teacher: scaffolds the organizer during the content class."},
  {std:1, g:"Take notes on key points of a 10-minute lesson using a partially completed guide, capturing at least 70% of the targeted points by the spring ELPT.", ev:"Once a month, guided notes from a 10-minute content lesson compared against a key of ten targeted points; record the percentage captured. Progress is 50% → 70% by the spring ELPT.", who:"EL teacher: teach note-taking on 5-minute clips with a partially completed guide, fade the blanks each month. Content teachers: provide the guide, post key terms before the lesson (Move 15, match the organizer to the thinking). Co-teacher: checks the notes at the end."},
  {std:6, g:"Tell whether a speaker is giving a fact, an opinion or a reason in short oral statements, 8 of 10 correct by March.", ev:"A ten-item oral sort once a month: the teacher reads statements, the student marks fact, opinion or reason. Score kept as x/10 in the folder; progress is 8/10 twice in a row.", who:"EL teacher: fact/opinion/reason signal words taught and posted (because, I think, the data show). Content teachers: label your own statements aloud for a month ('that's my opinion'). Peer: sort statements in pairs."},
  {std:2, g:"Follow a small-group discussion and respond to a classmate's idea appropriately in 3 of 4 structured talks.", ev:"During structured small-group talks, every other week, a four-box checklist: followed the thread, responded to a peer, response fit, needed a prompt. Progress is 3 of 4 boxes in three of the last four talks.", who:"EL teacher: discussion roles and response frames taught (Move 20, teach the conversation moves). Content teachers: structured talk twice a week with assigned turns (Move 19). Co-teacher: sits in the student's group once a week."},
 ],
 4: [
  {std:1, g:"Determine the central idea and how details support it in a grade-level lecture, podcast or video, scoring 3 of 4 on a listening rubric by the spring ELPT.", ev:"Every other week, a listening task from the content class (lecture clip, podcast segment) with a written central-idea response, scored on the 4-point rubric the ELA department already uses. Progress is a 3 in three of the last four.", who:"EL teacher: weekly grade-level listening tasks with the ELA rubric, central-idea frames. Content teachers: give the guiding question before any lecture or video, replay once. Co-teacher: checks the written response before it is turned in."},
  {std:6, g:"Identify a speaker's claim and one piece of evidence or reasoning in a grade-level oral argument, in 4 of 5 checks.", ev:"Once a month, a claim-and-evidence organizer completed while listening to a short grade-level argument (debate clip, persuasive speech), scored right/wrong for claim and for one piece of evidence. Progress is both right in 4 of 5.", who:"EL teacher: claim–evidence listening with debate clips and the organizer. Content teachers: name your claim and your evidence explicitly when you argue a point. ELA teacher: aligns with the argument unit."},
  {std:1, g:"Take independent notes on a full-period content lesson that capture the main points and key vocabulary, usable for a quiz, in 3 of 4 lessons.", ev:"Once a month the content teacher photographs the student's notes from a full lesson and rates them 1–3 for main points and vocabulary. Progress is a 3 in three of the last four, and the student using the notes on a quiz.", who:"EL teacher: teaches Cornell notes and abbreviations on content lectures. Content teachers: post the lesson outline, signal main points ('write this down'), allow a photo of the board. Co-teacher: reviews notes weekly for the first month."},
  {std:8, g:"Infer the meaning of unfamiliar academic words from spoken context and confirm them, 8 of 10 correct by March.", ev:"A monthly ten-item check: the teacher reads a sentence with one unfamiliar academic word, the student says what it probably means and why. Scored x/10; progress is 6/10 → 8/10.", who:"EL teacher: word-part and context-clue routine on heard sentences (Move 12, teach the word parts). Content teachers: define a new word in the sentence after you use it, once. Student: keeps a heard-words log."},
 ],
 5: [
  {std:1, g:"Comprehend fast-paced grade-level discussion, lectures and media without subtitles, scoring at the grade-level benchmark on listening tasks by the spring ELPT.", ev:"The content teacher's own listening-dependent assessments (quiz after lecture, video response), reported quarterly as a percentage. Progress is scores at or above the class median for two consecutive quarters.", who:"Content teachers: no change to pace; pre-teach only truly technical vocabulary. EL teacher: quarterly check-in and targeted pre-teaching on request. Student: self-monitors with a 'words I missed' list."},
  {std:6, g:"Evaluate a speaker's reasoning and identify when evidence does not support a claim, in 4 of 5 analyzed arguments.", ev:"Once a month, an argument-analysis task on a grade-level recording: identify the claim, the evidence, and one weakness. Scored on a 4-point rubric; progress is a 3 or 4 in four of five.", who:"EL teacher: monthly argument-analysis clinic on real speeches and editorials. ELA and history teachers: include ELs in the same argument-evaluation tasks as peers, no modification. Student: annotates transcripts."},
  {std:7, g:"Recognize shifts in register, tone and purpose (sarcasm, formality, persuasion) in oral language, 8 of 10 correct.", ev:"A ten-item register task each quarter: short clips, the student names the tone or purpose. Progress is 8/10 or better for two quarters.", who:"EL teacher: register and tone work with clips (sarcasm, formality, persuasion), discussion of pragmatics. Content teachers: name the register when you shift it. Student: notes examples from media."},
  {std:1, g:"Maintain Level 5 listening across content classes, with technical vocabulary monitored and pre-taught where needed.", ev:"A quarterly check-in with each content teacher (three questions: follows lectures, understands technical vocabulary, needs pre-teaching), logged on the LSP. Progress is 'no concerns' from all teachers for two quarters.", who:"EL teacher: quarterly check-in with each content teacher, pre-teaching on request. Content teachers: flag technical vocabulary a week ahead. Student: self-advocates when a lecture is unclear."},
 ],
},
S: {
 1: [
  {std:2, g:"Ask for help, a repeat or the bathroom using set phrases, independently, in 4 of 5 observed needs by January.", ev:"Each week the EL teacher tallies on a card whether the student used a phrase independently when a need arose (help, repeat, bathroom, 'I don't understand'). Progress is independent use in 4 of 5 observed needs for a month.", who:"EL teacher: the ten survival phrases taught, posted, rehearsed daily (First 100 Words, 'asking for help'). Content teachers: a phrase card on the desk; respond warmly every time it is used. Para: prompts the phrase before the student gives up."},
  {std:3, g:"Name and describe pictures and objects with single words and short phrases, 15 items in one minute by the spring ELPT.", ev:"A one-minute picture-naming probe every other week using the same 30-card deck; record words named correctly. Baseline the first week; progress is the count rising by at least two per month toward 15.", who:"EL teacher: daily picture naming with the same deck, tap-to-hear for pronunciation, Storm Lens on the classroom. Content teachers: ask the student to name objects used in the lesson. Family: flashcards at home."},
  {std:2, g:"Answer yes/no and either/or questions about self and the classroom with a word or phrase in 4 of 5 opportunities.", ev:"Once a week, five yes/no or either/or questions in conversation, tallied on the same card as the phrase check. Progress is a word or phrase answer (not just a nod) in 4 of 5 for three weeks.", who:"EL teacher: either/or questions first, yes/no second, in every lesson (Move 3, hand over a sentence frame). Content teachers: one question per class with two choices offered. Peer: partner asks the day's question."},
  {std:9, g:"Produce 10 memorized classroom sentences (greetings, requests, routines) intelligibly on demand by March.", ev:"A checklist of ten target sentences, checked monthly: the teacher prompts ('Greet me', 'Ask for a pencil'), ticks if the sentence is intelligible. Progress is the tick count rising each month to 10.", who:"EL teacher: one sentence a day rehearsed, chorally then alone, to a real person (office, cafeteria). Content teachers: greet and expect the greeting back. Para: practice the sentence of the day."},
 ],
 2: [
  {std:2, g:"Ask and answer simple questions in complete sentences about familiar topics, using sentence frames, in 4 of 5 partner talks by the spring ELPT.", ev:"Once a week during partner talk the teacher scores two exchanges 0–2 (no response / phrase / complete sentence) on the clipboard sheet. Progress is a 2 in 4 of 5 exchanges for a month, with and then without the frame visible.", who:"EL teacher: daily structured partner talk with question frames posted (Move 19). Content teachers: turn-and-talk with a frame on the board, 3 times a week (Move 4, talk before writing). Peer: trained partner who waits."},
  {std:3, g:"Retell a short story or describe a process in 3 to 5 simple sentences with picture support, scoring 2 of 3 on a retell rubric.", ev:"A one-minute recorded retell once a month (phone voice memo, saved to the student folder), scored on a 3-point retell rubric: sequence, detail, sentences. Progress is 1 → 2 → 3 across the semester; the recordings are the evidence.", who:"EL teacher: retell routine on picture sequences, first/then/finally frames, recorded monthly. Content teachers: ask for a 3-sentence retell of a procedure or event. Family: retell the day in the home language, too."},
  {std:4, g:"State an opinion and give one reason using a frame (I think ___ because ___) in 4 of 5 opportunities.", ev:"During class discussion, every other week, a tally of 'I think ___ because ___' (or equivalent) attempts and successes. Progress is a stated reason in 4 of 5 opinions.", who:"EL teacher: the opinion frame posted and used in every discussion (Move 3). Content teachers: 'I think ___ because ___' on the board for any opinion question. Peer: partners exchange opinions before whole-class talk."},
  {std:10, g:"Use present-tense subject–verb agreement and basic plurals in speech correctly 70% of the time in a one-minute sample.", ev:"A monthly one-minute speaking sample (same recording as the retell) with agreement and plural errors tallied. Progress is the error rate falling from roughly half to under 30%.", who:"EL teacher: agreement and plural mini-lessons with Sentence Lab pages, recast errors in talk. Content teachers: recast once, do not correct publicly (Move 7, grade the content, grow the English). Student: listens to own recording monthly."},
 ],
 3: [
  {std:3, g:"Explain a process or event from a content class in 5 or more connected sentences with some academic vocabulary, scoring 3 of 4 on a speaking rubric by the spring ELPT.", ev:"A two-minute recorded explanation once a month of a process from a current content unit, scored on the 4-point speaking rubric (sequence, connectors, vocabulary, clarity). Progress is a 3 in three of the last four recordings.", who:"EL teacher: process explanations rehearsed with sequence connectors and content vocabulary, recorded monthly. Content teachers: ask the student to explain a process to a partner before writing it (Move 4). Co-teacher: supplies the vocabulary list."},
  {std:4, g:"Make a claim and support it with two reasons or a piece of evidence in class discussion, without a frame, in 3 of 4 opportunities.", ev:"Every other week, a discussion checklist: made a claim, gave a reason, gave a second reason or evidence, no frame needed. Progress is all four boxes in 3 of 4 discussions.", who:"EL teacher: claim–reason–evidence talk routine, frames faded over the semester. Content teachers: ask 'what is your evidence?' as a follow-up every time. Co-teacher: tallies claims during discussion."},
  {std:2, g:"Participate in a small-group discussion by adding to, agreeing with or asking about a classmate's idea at least twice per discussion.", ev:"A weekly tally during one small-group discussion: contributions that add to, agree with or question a peer. Progress is at least two per discussion for a month, then consistently.", who:"EL teacher: conversation moves taught and posted (Move 20): add on, agree, ask. Content teachers: small-group discussion with talk cards twice a week (Move 21, share the air). Peer group: a rotating facilitator."},
  {std:9, g:"Present for 2 minutes on a prepared topic with notes, understood by the audience without repetition, by March.", ev:"A quarterly 2-minute presentation to the EL class scored on the 4-point rubric; a peer notes any point that had to be repeated. Progress is zero repeats and a rubric score of 3 by spring.", who:"EL teacher: presentation structure, notes on cards, rehearsal with a partner, recorded once. Content teachers: 1-minute share-outs in class. Family: rehearse at home in either language."},
 ],
 4: [
  {std:4, g:"Argue a position in a class discussion or debate with evidence from a text and respond to a counterargument, scoring 3 of 4 on a speaking rubric by the spring ELPT.", ev:"A structured academic controversy or mini-debate once a quarter, scored on the 4-point speaking rubric with a line for responding to a counterargument. Progress is a 3 or better by spring.", who:"EL teacher: structured academic controversy practice with evidence cards; counterargument frames (Move 20). History/ELA teachers: include the student in debates with the same roles as peers. Co-teacher: preps evidence the day before."},
  {std:3, g:"Summarize a grade-level text or lesson orally, including the central idea and key details, in 3 of 4 attempts.", ev:"Every other week, an oral summary of the day's text or lesson scored 1–3 (central idea, key details, order). Progress is a 3 in 3 of 4.", who:"EL teacher: oral summary routine (central idea + 3 details) on content texts, every other week. Content teachers: ask for an oral summary at the end of a reading. Peer: partner summaries, then share."},
  {std:7, g:"Shift between informal and academic register appropriately (partner talk vs. presenting), in 4 of 5 observed instances.", ev:"Monthly observation of two settings (partner talk, presenting or speaking to an adult) with a register checklist. Progress is appropriate register in 4 of 5 observed instances.", who:"EL teacher: register lessons — the same message to a friend, a teacher, an interviewer. Content teachers: name the register you expect ('present this formally'). Counselor: a mock interview in the spring."},
  {std:9, g:"Present for 3 to 4 minutes with varied sentence structures and transitions, using notes only, by March.", ev:"A quarterly 3–4 minute presentation with notes only, scored on the 4-point rubric with a line for sentence variety and transitions. Progress is a 3 by the spring quarter.", who:"EL teacher: presentation coaching on transitions and sentence variety, one rehearsal recorded. Content teachers: a 3-minute presentation slot each quarter. Peer: feedback with a two-item checklist."},
 ],
 5: [
  {std:2, g:"Participate in fast-paced grade-level discussion, disagree politely, and build on others' ideas at the grade-level benchmark by the spring ELPT.", ev:"The content teacher's discussion rubric (most departments have one), reported quarterly. Progress is a score at the class benchmark for two quarters.", who:"Content teachers: full participation in discussion with the class rubric. EL teacher: quarterly check on discussion rubric scores, coaching on request. Student: sets a participation target per class."},
  {std:9, g:"Present without notes for 5 minutes with precise vocabulary and few errors that affect meaning.", ev:"A quarterly 5-minute presentation without notes, scored on the 4-point rubric, with vocabulary precision and errors-affecting-meaning noted. Progress is a 4 by spring.", who:"EL teacher: presentation coaching twice a semester, focus on precision. Content teachers: presentations with the same rubric as peers. Student: records and self-evaluates."},
  {std:7, g:"Speak appropriately in an interview, a formal presentation and a casual exchange, adjusting register in each, in 3 of 3 observed settings.", ev:"One mock interview and one formal presentation per semester, each scored for register on a 3-point scale, plus a casual-exchange observation. Progress is appropriate register in all three.", who:"Counselor and EL teacher: a mock interview each semester. Content teachers: formal presentation opportunities. Student: notes register choices after each."},
  {std:10, g:"Maintain Level 5 speaking; refine precision and complex grammar (conditionals, passive, reported speech) in academic talk.", ev:"A semester speaking sample analyzed for complex structures used correctly (conditionals, passive, reported speech). Progress is each structure appearing correctly at least once.", who:"EL teacher: complex grammar in talk (conditionals, reported speech) through debate and role-play. ELA teacher: holds the student to the grade-level speaking standard. Student: semester self-recording."},
 ],
},
R: {
 1: [
  {std:1, g:"Read and understand environmental print, labels, schedules and single sentences with picture support, 8 of 10 correct by January.", ev:"A ten-item picture-to-sentence match every other week using print from the building (signs, schedule, labels). Recorded x/10; progress is 8/10 twice in a row.", who:"EL teacher: daily environmental-print walk and label reading; schedule read together each morning. Content teachers: picture-labeled directions and materials. Para: reads the schedule with the student."},
  {std:8, g:"Read 50 high-frequency school words on sight by the spring ELPT.", ev:"The First 100 Words sight-word check once a month: flash 50 words, tally read correctly within 3 seconds. Progress is the count rising monthly toward 50.", who:"EL teacher: First 100 Words sight-word work, 10 a week, printable flashcards. Content teachers: the same words on the word wall (Move 11). Family: flashcards at home, five minutes a night."},
  {std:8, g:"Use a bilingual dictionary or glossary to find the meaning of a word independently, in 4 of 5 attempts by March.", ev:"During independent reading every other week, the teacher notes whether the student opened the dictionary/glossary and found the word without being told to. Progress is 4 of 5 attempts independent.", who:"EL teacher: teach dictionary use explicitly, bilingual dictionary on the desk at all times. Content teachers: allow and expect the dictionary (Move 29, use the home language as a tool). Para: prompts 'look it up' before giving the answer."},
  {std:1, g:"Match 10 content words to pictures or definitions after a lesson, 8 of 10 correct.", ev:"A weekly ten-item match of that week's content words to pictures or definitions. Progress is 8/10 in three consecutive weeks.", who:"EL teacher: content words with pictures previewed each Monday (Move 2). Content teachers: word wall with images; matching task as the exit ticket. Peer: bilingual partner for labels."},
 ],
 2: [
  {std:1, g:"Read a short text (4 to 6 sentences) on a familiar topic and identify the main idea and one detail, in 4 of 5 checks by the spring ELPT.", ev:"A short passage (4–6 sentences) with three questions every other week, taken from the EL class's leveled texts. Scored x/3; progress is 3/3 in 4 of the last 5.", who:"EL teacher: short leveled texts daily with main-idea frames; think-aloud first (Move 16). Content teachers: a leveled version or a summary paragraph of the week's reading (Move 6, make the text reachable). Co-teacher: previews the text."},
  {std:8, g:"Use context clues and cognates to work out the meaning of unfamiliar words in a short text, 6 of 10 correct by March.", ev:"A monthly ten-item task: unfamiliar words underlined in a short text, student writes or says the likely meaning; Cognate Hunt output used for the cognate items. Progress is 4/10 → 6/10 by March.", who:"EL teacher: cognate hunt weekly (Move 10, Cognate Hunt tool), context-clue routine with a frame. Content teachers: run the week's reading through Cognate Hunt and post the wall. Family: cognate list home."},
  {std:1, g:"Follow written multi-step directions for a classroom task independently, in 4 of 5 tasks.", ev:"A weekly tally of whether the student completed a classroom task from written directions without asking. Progress is 4 of 5 tasks for a month.", who:"EL teacher: written-direction tasks daily, numbered steps, practice without asking. Content teachers: numbered written directions with a verb first; a model of the finished product. Para: fades prompting."},
  {std:3, g:"Answer literal questions (who, what, where, when) about a leveled text in writing or speech, 8 of 10 correct.", ev:"Every other week, ten literal questions on a leveled text, answered orally or in writing. Scored x/10; progress is 8/10 twice in a row.", who:"EL teacher: literal-question routine on leveled texts, underline the answer first. Content teachers: literal questions on the reading before inferential ones. Peer: partner reading with question cards."},
 ],
 3: [
  {std:1, g:"Read an adapted grade-level text with vocabulary preview and identify the main idea, supporting details and sequence, scoring 3 of 4 on a comprehension rubric by the spring ELPT.", ev:"Every other week, a comprehension task on an adapted grade-level text (main idea, two details, sequence) scored 0–4. Progress is a 3 or better in three of the last four.", who:"EL teacher: adapted grade-level texts with vocabulary preview, main-idea organizer, sequence words (Moves 2, 15). Content teachers: provide the preview list and an adapted text when available (Move 6). Co-teacher: reads alongside."},
  {std:8, g:"Determine the meaning of academic and content words using context, word parts and cognates, 8 of 10 correct by March.", ev:"A monthly ten-item word-meaning check drawn from that month's content texts, with the strategy used (context, word part, cognate) noted. Progress is 8/10 by March.", who:"EL teacher: word parts (Move 12), cognates (Move 10), context clues taught as a three-step routine. Content teachers: point out a root or cognate once a lesson. Student: personal word log by strategy."},
  {std:6, g:"Distinguish fact from opinion and identify the author's point in a short informational text, in 4 of 5 checks.", ev:"Once a month, a fact/opinion sort of ten sentences plus one 'what is the author's point?' question on a short informational text. Progress is 8/10 and the author's point right in 4 of 5.", who:"EL teacher: fact/opinion signal words, author's-point frame on informational texts. History and science teachers: ask 'what is the author's point?' after each reading. Peer: pairs sort statements."},
  {std:3, g:"Locate evidence in a text to answer a text-dependent question, citing the sentence, in 4 of 5 questions.", ev:"Every other week, five text-dependent questions where the student must underline the sentence that answers each. Progress is the right sentence in 4 of 5.", who:"EL teacher: evidence-hunting routine — underline, then answer (Move 14, annotate with a purpose). Content teachers: text-dependent questions with 'underline where you found it'. Co-teacher: checks the underlines."},
 ],
 4: [
  {std:1, g:"Read a grade-level literary or informational text with minimal support and determine the central idea, how it develops and the author's purpose, scoring 3 of 4 by the spring ELPT.", ev:"Every other week, a grade-level passage with central idea, development and author's-purpose questions, scored on the ELA 4-point rubric. Progress is a 3 in three of the last four.", who:"EL teacher: grade-level passages with the ELA rubric, central-idea and purpose frames; annotation (Move 14). ELA teacher: same texts as peers with the vocabulary preview. Co-teacher: supports during close reading."},
  {std:6, g:"Identify a claim, the evidence used and whether it is sufficient in a grade-level argument text, in 4 of 5 analyses.", ev:"A monthly claim–evidence organizer on a grade-level argument text, marked for claim found, evidence found, sufficiency judged. Progress is all three in 4 of 5.", who:"EL teacher: claim–evidence–sufficiency organizer on argument texts, monthly. History and ELA teachers: argument texts with the organizer provided. Student: annotates claims in color."},
  {std:8, g:"Interpret figurative language, multiple-meaning words and technical terms in grade-level text, 8 of 10 correct.", ev:"A monthly ten-item check on figurative, multiple-meaning and technical words taken from the student's own content texts. Progress is 8/10 twice in a row.", who:"EL teacher: figurative and multiple-meaning words from the student's own texts, weekly. Content teachers: flag technical and multiple-meaning words on the board. Student: word log."},
  {std:3, g:"Compare how two texts treat the same topic, citing evidence from each, scoring 3 of 4 on a rubric.", ev:"A quarterly paired-text task from the ELA class scored on its rubric. Progress is a 3 by spring.", who:"EL teacher: paired-text practice with a comparison organizer. ELA teacher: the paired-text task on the department rubric. Co-teacher: previews both texts."},
 ],
 5: [
  {std:1, g:"Read grade-level and primary-source texts independently at the grade-level benchmark on content and state assessments by the spring ELPT.", ev:"Content-class and benchmark reading assessments reported quarterly as a percentage or scale score. Progress is at or above the grade benchmark for two quarters.", who:"Content teachers: grade-level texts without modification; vocabulary preview only for technical terms. EL teacher: quarterly check of reading scores and support on request. Student: independent reading log."},
  {std:6, g:"Evaluate the reasoning and evidence in complex arguments and identify bias or missing evidence, in 4 of 5 analyses.", ev:"A monthly argument-evaluation task on a complex text (editorial, primary source), scored on a 4-point rubric that includes bias or missing evidence. Progress is a 3 or 4 in 4 of 5.", who:"EL teacher: monthly argument evaluation on editorials and primary sources, bias and missing evidence. History teacher: the same tasks as peers (DBQ practice). Student: annotates sources."},
  {std:5, g:"Gather and compare information from three sources on a research question, noting credibility, by the end of the semester.", ev:"A semester research task: three sources on one question with a one-line credibility note each, scored on the content class's research rubric. Progress is the task completed at benchmark.", who:"ELA or history teacher: the semester research task with the class rubric. EL teacher: source-credibility mini-lesson and a check-in at the midpoint. Librarian: database orientation."},
  {std:8, g:"Maintain Level 5 reading; build technical vocabulary in each content area, tracked by a personal word log.", ev:"A personal word log reviewed each quarter with the EL teacher: new technical terms per content area, with a sentence each. Progress is the log growing every quarter and the student using the terms in writing.", who:"Student: keeps the technical word log by subject. EL teacher: reviews it quarterly. Content teachers: flag the five key terms per unit."},
 ],
},
W: {
 1: [
  {std:9, g:"Write name, date, labels and copied sentences accurately, and complete a simple form, independently by January.", ev:"A weekly check of the student's own heading, labels and a copied sentence from class work, scored right/wrong on a dated checklist. Progress is four consecutive weeks correct.", who:"EL teacher: heading and label routine daily; forms practice weekly (First 100 Words, forms). Content teachers: a heading model on the board. Para: checks the heading before work is turned in."},
  {std:3, g:"Write 3 simple sentences about self, family or a picture using a sentence frame and word bank, by the spring ELPT.", ev:"Every other week, a three-sentence sample from a frame and word bank, scored 0–3 (one point per complete, meaningful sentence) and kept in the writing folder. Progress is 3/3 in three of the last four.", who:"EL teacher: daily frame-supported sentence writing with a word bank; Sentence Lab page per week. Content teachers: one frame sentence as the exit ticket (Move 3). Family: three sentences about the day at home."},
  {std:8, g:"Label 10 pictures or diagram parts with the correct content word, 8 of 10 correct after a lesson.", ev:"A weekly labeling task of a diagram or picture set from the content unit, ten labels, scored x/10. Progress is 8/10 in three consecutive weeks.", who:"EL teacher: diagram labeling with the week's content words. Science and social studies teachers: labeled diagrams as the task for the student (Move 6). Peer: partner labels, then compares."},
  {std:10, g:"Use capital letters and end punctuation in copied and frame-supported sentences 80% of the time.", ev:"The monthly writing sample tallied for capitals and end punctuation. Progress is 50% → 80% across the semester.", who:"EL teacher: capital-and-period check as the last step of every piece of writing, a two-item checklist taped to the desk. Content teachers: the same two-item check. Student: self-checks before turning in."},
 ],
 2: [
  {std:3, g:"Write a paragraph of 4 to 6 simple sentences on a familiar topic with a topic sentence, using a word bank, scoring 2 of 3 on a rubric by the spring ELPT.", ev:"Every other week, a paragraph on a familiar topic from a word bank, scored on a 3-point rubric (topic sentence, 4+ sentences, on topic) and kept in the writing folder. Progress is a 2 or 3 in 4 of the last 5.", who:"EL teacher: paragraph frame (topic sentence + 3 + closing) with a word bank, every other week; Sentence Lab for structure. Content teachers: a word bank with every writing task (Move 3). Co-teacher: edits with the student."},
  {std:4, g:"Write an opinion with one reason using a frame (I think ___ because ___), in 4 of 5 prompts.", ev:"A weekly opinion quick-write (three minutes) checked for a stated reason. Progress is a reason present in 4 of 5.", who:"EL teacher: 3-minute opinion quick-write daily with the frame posted. Content teachers: one opinion question with the frame weekly. Peer: swap and find the reason."},
  {std:10, g:"Use present and past tense correctly 70% of the time in a short writing sample by March.", ev:"The monthly writing sample with verb-tense errors tallied against verbs used. Progress is accuracy rising from about half to 70% by March.", who:"EL teacher: tense mini-lessons with Sentence Lab, timeline on the wall, verb-check step before turning in. Content teachers: do not mark tense errors on content work (Move 7). Student: circles own verbs monthly."},
  {std:9, g:"Write complete sentences (subject and verb) 80% of the time in independent writing.", ev:"The monthly sample counted for complete sentences out of sentences attempted. Progress is 80% for two months running.", who:"EL teacher: 'subject + verb' check on every sentence, sentence-combining practice (Move 23, grow the sentence). Content teachers: accept phrase answers on content; require sentences on the exit ticket only. Student: self-check."},
 ],
 3: [
  {std:3, g:"Write a paragraph with a topic sentence, three details and a concluding sentence, using some academic vocabulary, scoring 3 of 4 on a rubric by the spring ELPT.", ev:"Every other week, a paragraph scored on the 4-point rubric (topic sentence, three details, conclusion, academic vocabulary), kept in the folder with the previous one for comparison. Progress is a 3 in three of the last four.", who:"EL teacher: paragraph structure with the 4-point rubric, academic word bank, every other week (Move 22, from sentence to paragraph). Content teachers: paragraph writing with the rubric and word bank in content class. Co-teacher: conferences monthly."},
  {std:4, g:"Write a claim supported by two pieces of evidence from a text, with a sentence explaining each, in 3 of 4 prompts.", ev:"A monthly claim–evidence–reasoning paragraph from a content-class text, scored with the CER checklist the science department uses. Progress is all three parts present in 3 of 4.", who:"EL teacher: CER paragraph routine with frames, monthly. Science teacher: the CER checklist on every lab conclusion; Social studies: claim–evidence on documents. Co-teacher: checks each part."},
  {std:9, g:"Use transitions (first, however, because, as a result) to connect ideas across a paragraph, at least 3 per paragraph.", ev:"A transition count on the monthly sample (circle each one). Progress is three or more per paragraph, used correctly, for two months.", who:"EL teacher: transition word bank by purpose posted and required; model paragraphs marked up. Content teachers: the same transition bank on the wall. Student: circles transitions before turning in."},
  {std:10, g:"Edit own writing for subject–verb agreement, plurals and past tense using a checklist, fixing 70% of errors.", ev:"Once a month the student edits a previous sample with the editing checklist; the teacher counts errors before and after. Progress is 70% of errors fixed independently.", who:"EL teacher: editing checklist taught and used on every piece; one error type per week (Move 24, feedback that sticks). Content teachers: return one piece a month for editing, not regrading. Student: edits own draft first."},
 ],
 4: [
  {std:4, g:"Write a multi-paragraph argument with a claim, evidence from two sources, reasoning and a counterclaim, scoring 3 of 4 on a grade-level rubric by the spring ELPT.", ev:"A quarterly multi-paragraph argument scored on the ELA department's rubric, with the counterclaim line checked. Progress is a 3 by spring.", who:"EL teacher: argument structure with the ELA rubric, counterclaim frames, evidence from two sources. ELA teacher: the same essay task as peers with the rubric. Co-teacher: outlining conference."},
  {std:3, g:"Write a summary, lab report or analysis of a grade-level text that includes the central idea and key details, in 3 of 4 assignments.", ev:"The content teacher's own writing assignments (summary, lab report, analysis) reported monthly with the rubric score. Progress is a passing score in 3 of 4.", who:"Content teachers: summaries, lab reports and analyses with the rubric and a model. EL teacher: genre structure mini-lessons matched to what is due. Co-teacher: planning conference before each."},
  {std:9, g:"Vary sentence structure (compound, complex) and use precise vocabulary so that errors do not affect meaning, in 3 of 4 samples.", ev:"The monthly sample scored for sentence variety (count compound and complex sentences) and for errors that affect meaning. Progress is variety up, meaning errors down to two or fewer per page.", who:"EL teacher: sentence-combining and variety work (Move 23), precision word choice. ELA teacher: holds the student to the grade rubric for structure. Student: revises one paragraph a week for variety."},
  {std:5, g:"Write a short research piece citing two sources in the required format by the end of the semester.", ev:"A semester research piece with two cited sources, scored on the class rubric with a line for citation format. Progress is completed at benchmark.", who:"Content or ELA teacher: the research task with the class rubric and citation format. EL teacher: citation mini-lesson, midpoint check. Librarian: source help."},
 ],
 5: [
  {std:4, g:"Write research-based arguments and informational pieces at the grade-level benchmark with few errors that affect meaning, by the spring ELPT.", ev:"Content-class and state writing assessments reported quarterly. Progress is a score at the grade benchmark for two quarters.", who:"ELA and content teachers: grade-level writing tasks, same rubric as peers. EL teacher: quarterly review of scores, coaching on request. Student: tracks rubric scores."},
  {std:7, g:"Write in multiple genres and registers (lab report, formal letter, narrative, analysis) adjusting tone and vocabulary to each, in 3 of 3 assigned genres.", ev:"A semester portfolio of three genres, each scored for fit of tone and vocabulary to purpose on a 3-point scale. Progress is a 3 in all three.", who:"ELA teacher: assigns the three genres across the semester. EL teacher: register and tone conference before each. Student: builds the portfolio with a reflection on each piece."},
  {std:9, g:"Revise own drafts for clarity, cohesion and register with minimal teacher direction, improving a rubric score by one level in 3 of 4 revisions.", ev:"Draft and final of each major piece kept together; rubric scores compared. Progress is the final a level above the draft in 3 of 4 pieces, with revisions the student made unprompted.", who:"ELA teacher: requires a draft and a final for major pieces. EL teacher: revision conference on the first two; student revises independently after. Student: keeps both versions."},
  {std:10, g:"Maintain Level 5 writing; refine complex grammar (conditionals, passive voice, reported speech) and academic register.", ev:"A semester writing sample analyzed for complex grammar and register. Progress is complex structures used correctly and no register slips in academic writing.", who:"EL teacher: complex grammar in context (conditionals, passive, reported speech) through the student's own writing. ELA teacher: grade-level expectations for register. Student: semester self-analysis of a sample."},
 ],
},
};
window.ELP_STD = {1:"Construct meaning",2:"Participate in exchanges",3:"Speak and write about texts",4:"Claims with evidence",5:"Research",6:"Analyze arguments",7:"Adapt language to audience",8:"Word meaning",9:"Clear and coherent",10:"Standard English"};
