/* Languages for printing the Language Service Plan.

   Every fixed string on the form — headings, labels, the checkbox lists,
   the drop-down choices, the signature lines — in the family's language.
   What the teacher typed (goals, strategies, evidence, notes) stays as
   typed; the printed page says so and asks for an interpreter to walk the
   family through it.

   To add a language: copy the Spanish block, translate the right-hand
   side, keep ELPT / MAAP / MSIS / IEP / ELPA21 as they are, and add the
   code to LSP_LANG_NAMES. A key that is missing simply prints in English. */
window.LSP_LANG_NAMES = { en: "English", es: "Español" };
window.LSP_LANG = {
es: {
"Language Service Plan (LSP)": "Plan de Servicios Lingüísticos (LSP)",
"English Learner ·": "Aprendiz de inglés ·",
"· School year": "· Año escolar",
"Confidential · FERPA": "Confidencial · FERPA",
"1 · Student": "1 · Estudiante",
"2 · Identification trail": "2 · Identificación",
"3 · English proficiency": "3 · Dominio del inglés",
"4 · Program & services": "4 · Programa y servicios",
"5 · Instructional accommodations": "5 · Adaptaciones en el salón",
"6 · Assessment accommodations": "6 · Adaptaciones en las evaluaciones",
"7 · Grading, promotion & retention": "7 · Calificaciones, promoción y retención",
"8 · Goals by domain": "8 · Metas por dominio",
"9 · Status, monitoring & review": "9 · Estado, seguimiento y revisión",
"10 · Distribution & signatures": "10 · Distribución y firmas",
"Student is": "El/la estudiante es",
"New EL — identified this year": "Nuevo EL — identificado este año",
"Active EL — continuing": "EL activo — continúa",
"Monitored — Year 1 after exit": "En seguimiento — Año 1 después de salir",
"Monitored — Year 2": "En seguimiento — Año 2",
"Monitored — Year 3": "En seguimiento — Año 3",
"Monitored — Year 4": "En seguimiento — Año 4",
"Name": "Nombre",
"Student ID (MSIS)": "Número de estudiante (MSIS)",
"Grade": "Grado",
"School": "Escuela",
"Home language": "Idioma del hogar",
"Birth country": "País de nacimiento",
"First enrolled in U.S. schools": "Primera inscripción en escuelas de EE. UU.",
"Enrolled in this district": "Inscripción en este distrito",
"Years in EL program": "Años en el programa EL",
"0 (first year)": "0 (primer año)",
"Prior schooling": "Escolaridad previa",
"Continuous": "Continua",
"Interrupted / limited (SLIFE)": "Interrumpida / limitada (SLIFE)",
"Unknown — ask family": "Se desconoce — preguntar a la familia",
"IEP / 504": "IEP / 504",
"None": "Ninguno",
"IEP — see plan": "IEP — ver el plan",
"504 — see plan": "504 — ver el plan",
"Referral in progress": "Remisión en proceso",
"EL teacher of record (contact)": "Maestro/a de EL responsable (contacto)",
"Student Evaluation Team (EL committee)": "Equipo de Evaluación del Estudiante (comité EL)",
"— check each member; the signature block follows": "— marque cada integrante; las firmas siguen",
"EL teacher": "Maestro/a de EL",
"Classroom teacher(s)": "Maestro(s) de clase",
"Principal / designee": "Director/a o designado",
"Counselor": "Consejero/a",
"EL coordinator / Title III": "Coordinador/a de EL / Título III",
"Parent / guardian": "Padre, madre o tutor",
"Student": "Estudiante",
"Interpreter": "Intérprete",
"Special-education teacher": "Maestro/a de educación especial",
"required": "obligatorio",
"Home Language Survey → screener → parent notification, each dated": "Encuesta del idioma del hogar → prueba inicial → notificación a los padres, cada una con fecha",
"continuing EL — identification is on file from the first year; this year needs the annual notice and the parent's response": "EL que continúa — la identificación está archivada desde el primer año; este año requiere el aviso anual y la respuesta de los padres",
"Home Language Survey date": "Fecha de la Encuesta del idioma del hogar",
"Screener given": "Prueba inicial aplicada",
"ELPT Screener (ELPA21)": "Prueba inicial ELPT (ELPA21)",
"Screener date": "Fecha de la prueba inicial",
"Parent notification sent": "Notificación enviada a los padres",
"Notification language": "Idioma de la notificación",
"Interpreter for the conference": "Intérprete para la reunión",
"Yes — in person": "Sí — en persona",
"Yes — phone or video service": "Sí — por teléfono o video",
"Bilingual staff member": "Personal bilingüe",
"Not needed — parent proficient in English": "No necesario — el padre/madre domina el inglés",
"Offered and declined by parent": "Ofrecido y rechazado por el padre/madre",
"Not yet arranged": "Aún no se ha organizado",
"Annual notification (continuing ELs)": "Notificación anual (EL que continúan)",
"Parent response": "Respuesta de los padres",
"Accepted services": "Aceptó los servicios",
"Declined services (school still obligated)": "Rechazó los servicios (la escuela sigue obligada)",
"No response yet": "Sin respuesta todavía",
"most recent ELPT or screener, by domain": "ELPT o prueba inicial más reciente, por dominio",
"Listening": "Comprensión auditiva",
"Speaking": "Expresión oral",
"Reading": "Lectura",
"Writing": "Escritura",
"Overall determination": "Determinación general",
"Emerging": "Emergente",
"Progressing": "En progreso",
"Proficient": "Competente",
"Focus domain this year": "Dominio prioritario este año",
"Test / date": "Prueba / fecha",
"ELPT domain exemption": "Exención de un dominio del ELPT",
"None — all four domains": "Ninguna — los cuatro dominios",
"Listening (IEP)": "Comprensión auditiva (IEP)",
"Speaking (IEP)": "Expresión oral (IEP)",
"Reading (IEP)": "Lectura (IEP)",
"Writing (IEP)": "Escritura (IEP)",
"ELPT history": "Historial del ELPT",
"— every prior year the student has a score": "— cada año anterior con puntaje",
"Year": "Año",
"Overall": "General",
"Daily ESL/ELD class with a certified EL teacher": "Clase diaria de ESL/ELD con maestro/a de EL certificado",
"Co-teaching / push-in support in content classes": "Co-enseñanza / apoyo dentro de las clases de contenido",
"Pull-out small-group language instruction": "Instrucción de idioma en grupo pequeño fuera del salón",
"Sheltered content instruction (SIOP-style) in core classes": "Instrucción de contenido con apoyo lingüístico (estilo SIOP) en las materias básicas",
"Newcomer program / bridge (time-limited)": "Programa para recién llegados (por tiempo limitado)",
"Bilingual paraprofessional support": "Apoyo de un/a asistente bilingüe",
"Tutoring / after-school language support": "Tutoría / apoyo de idioma después de clases",
"Monitoring only (former EL)": "Solo seguimiento (ex EL)",
"EL instruction minutes per week": "Minutos de instrucción EL por semana",
"450 — one 90-minute block daily": "450 — un bloque de 90 minutos al día",
"250 — one 50-minute period daily": "250 — un periodo de 50 minutos al día",
"225 — 45 minutes daily": "225 — 45 minutos al día",
"150 — 30 minutes daily, pull-out": "150 — 30 minutos al día, fuera del salón",
"90 — co-teaching / push-in, 2 × 45": "90 — co-enseñanza, 2 × 45",
"0 — monitoring only (former EL)": "0 — solo seguimiento (ex EL)",
"Content classes with language support (list)": "Clases de contenido con apoyo de idioma (lista)",
"If dual-identified (IEP/504): how language and disability goals are coordinated": "Si tiene IEP/504: cómo se coordinan las metas de idioma y de discapacidad",
"If services declined: what continues anyway": "Si se rechazaron los servicios: lo que continúa de todos modos",
"Vocabulary preview before lessons": "Vocabulario anticipado antes de la lección",
"Sentence frames & word banks": "Marcos de oración y bancos de palabras",
"Visuals, realia & graphic organizers": "Imágenes, objetos reales y organizadores gráficos",
"Home-language support (bilingual peer, app for comprehension, bilingual notes)": "Apoyo en el idioma del hogar (compañero bilingüe, aplicación para comprender, notas bilingües)",
"Leveled / modified texts with grade-level vocabulary": "Textos nivelados o adaptados con vocabulario del grado",
"Reduced length or alternate response format": "Menor extensión o formato de respuesta alternativo",
"Oral or recorded responses accepted": "Se aceptan respuestas orales o grabadas",
"Directions repeated & clarified; comprehension checks": "Instrucciones repetidas y aclaradas; comprobación de comprensión",
"Extended wait time": "Tiempo de espera ampliado",
"Preferential seating": "Asiento preferencial",
"Content scored for accuracy; language errors not penalized on non-ELA work": "Se califica el contenido; los errores de idioma no se penalizan fuera de la clase de inglés",
"Bilingual dictionary in class": "Diccionario bilingüe en clase",
"classroom and state tests (MAAP, ELPT) — must match the Mississippi Testing Accommodations Manual and be used routinely in class": "pruebas del salón y del estado (MAAP, ELPT) — deben coincidir con el Manual de Adaptaciones de Mississippi y usarse de forma habitual en clase",
"Extended time (amount specified) — class & state (MTAM #20)": "Tiempo adicional (cantidad especificada) — salón y estado (MTAM #20)",
"Word-to-word bilingual glossary (print) — class & MAAP (MTAM #81; not allowed on ELPT)": "Glosario bilingüe palabra por palabra (impreso) — salón y MAAP (MTAM #81; no se permite en el ELPT)",
"Directions read aloud, repeated, clarified in English — class & state": "Instrucciones leídas en voz alta, repetidas y aclaradas en inglés — salón y estado",
"Test questions & answer choices read aloud / text-to-speech — class & MAAP (MTAM #55; passages not read; not ELPT Reading)": "Preguntas y opciones leídas en voz alta / texto a voz — salón y MAAP (MTAM #55; no se leen los pasajes; no en Lectura del ELPT)",
"Small-group administration — class & state": "Aplicación en grupo pequeño — salón y estado",
"Supervised breaks — class & state": "Descansos supervisados — salón y estado",
"Preferential seating — class & state": "Asiento preferencial — salón y estado",
"Classroom only: translated directions / home-language glossary (primary language not permitted on ELPT)": "Solo en el salón: instrucciones traducidas / glosario en el idioma del hogar (no se permite el idioma materno en el ELPT)",
"Classroom only: sentence frames / word bank on classroom tests": "Solo en el salón: marcos de oración / banco de palabras en las pruebas del salón",
"Classroom only: oral response on classroom tests": "Solo en el salón: respuesta oral en las pruebas del salón",
"Classroom only: reduced-length classroom tests": "Solo en el salón: pruebas del salón más cortas",
"State assessments this student takes this year": "Evaluaciones estatales que toma este año",
"— the accommodations above apply to each one checked": "— las adaptaciones de arriba se aplican a cada una marcada",
"ELPT (ELPA21) — listening, speaking, reading, writing": "ELPT (ELPA21) — comprensión auditiva, expresión oral, lectura, escritura",
"every EL, K–12, each spring until exit": "todo EL, K–12, cada primavera hasta salir del programa",
"Kindergarten Readiness Assessment — pre and post": "Evaluación de preparación para kínder — inicio y fin",
"K–3 universal reading screener": "Prueba universal de lectura K–3",
"K–3, three times a year": "K–3, tres veces al año",
"MAAP English Language Arts": "MAAP Lengua y Literatura en inglés",
"grades 3–8 · grade 3 is the reading gate (Literacy-Based Promotion Act)": "grados 3–8 · el grado 3 es la prueba de promoción en lectura",
"MAAP Mathematics": "MAAP Matemáticas",
"grades 3–8": "grados 3–8",
"MAAP Science": "MAAP Ciencias",
"grades 5 and 8": "grados 5 y 8",
"MAAP End-of-Course · English II": "MAAP Fin de curso · Inglés II",
"MAAP End-of-Course · Algebra I": "MAAP Fin de curso · Álgebra I",
"MAAP End-of-Course · Biology I": "MAAP Fin de curso · Biología I",
"MAAP End-of-Course · U.S. History": "MAAP Fin de curso · Historia de EE. UU.",
"when enrolled in the course": "cuando está inscrito en el curso",
"when enrolled — high school, or grade 8 if taking it early": "cuando está inscrito — preparatoria, o grado 8 si lo toma antes",
"ACT — state administration": "ACT — aplicación estatal",
"grade 11": "grado 11",
"ACT WorkKeys": "ACT WorkKeys",
"grade 11–12, career and technical pathways": "grados 11–12, programas técnicos y vocacionales",
"MAAP-A (alternate assessment)": "MAAP-A (evaluación alternativa)",
"IEP-team decision only · significant cognitive disability": "solo por decisión del equipo IEP · discapacidad cognitiva significativa",
"Notes for the District Test Coordinator": "Notas para el Coordinador de Pruebas del Distrito",
"First-year EL and the ELA state test": "EL de primer año y la prueba estatal de inglés",
"Not applicable — not in first 12 months": "No aplica — no está en los primeros 12 meses",
"DTC confirmed: takes ELA with accommodations": "Confirmado por el DTC: toma la prueba de inglés con adaptaciones",
"DTC confirmed: exempt from this year's ELA administration": "Confirmado por el DTC: exento de la prueba de inglés este año",
"Not yet confirmed with the DTC": "Aún no confirmado con el DTC",
"Report card / progress report notes that the student receives EL supports and accommodations": "La boleta / informe de progreso indica que el estudiante recibe apoyos y adaptaciones EL",
"Parents told, in a language they understand, what accommodations are used and how grades are earned": "Se informó a los padres, en un idioma que entienden, qué adaptaciones se usan y cómo se obtienen las calificaciones",
"Progress reports and report cards sent home translated or orally interpreted": "Informes de progreso y boletas enviados a casa traducidos o interpretados oralmente",
"Student is not retained solely because of English proficiency": "El estudiante no se retiene únicamente por su nivel de inglés",
"Promotion decisions consider ELPT growth and time in U.S. schools, not grade-level English alone": "La promoción considera el avance en el ELPT y el tiempo en escuelas de EE. UU., no solo el inglés del grado",
"Retention is under consideration for this student": "Se está considerando la retención de este estudiante",
"Interventions documented showing English is not the barrier — plus the parent meeting date and the parents' signed agreement": "Intervenciones documentadas que muestran que el inglés no es la barrera — más la fecha de la reunión con los padres y su acuerdo firmado",
"Strategies / who": "Estrategias / quién",
"— what is done, and by whom": "— qué se hace y quién lo hace",
"Evidence of progress": "Evidencia de progreso",
"— instrument, how often, where kept, what counts": "— instrumento, frecuencia, dónde se guarda, qué cuenta",
"Status (MSIS)": "Estado (MSIS)",
"Active EL": "EL activo",
"Active EL — parent declined services": "EL activo — los padres rechazaron los servicios",
"Monitored Year 1": "En seguimiento, año 1",
"Monitored Year 2": "En seguimiento, año 2",
"Monitored Year 3": "En seguimiento, año 3",
"Monitored Year 4": "En seguimiento, año 4",
"Exit criterion": "Criterio de salida",
"Level 4 or higher in each ELPT domain, same administration": "Nivel 4 o más en cada dominio del ELPT, en la misma aplicación",
"Plan written": "Plan redactado",
"Reviewed after ELPT results": "Revisado tras los resultados del ELPT",
"Nine-weeks reviews": "Revisiones cada nueve semanas",
"— grades, attendance, ELPT progress; teachers initial changes": "— calificaciones, asistencia, avance en el ELPT; los maestros firman los cambios",
"Q1 date · initials": "T1 fecha · iniciales",
"Q2 date · initials": "T2 fecha · iniciales",
"Q3 date · initials": "T3 fecha · iniciales",
"Q4 / end-of-year · initials": "T4 / fin de año · iniciales",
"Review notes / changes": "Notas de revisión / cambios",
"Teachers of record receiving this plan": "Maestros que reciben este plan",
"Given to teachers on": "Entregado a los maestros el",
"Copy to cumulative folder on": "Copia al expediente el",
"Translated / interpreted for parent": "Traducido / interpretado para los padres",
"Translated written copy given": "Se entregó copia escrita traducida",
"Interpreted orally at the conference": "Interpretado oralmente en la reunión",
"Both — translated copy and interpretation": "Ambos — copia traducida e interpretación",
"Not needed — parent reads English": "No necesario — el padre/madre lee inglés",
"Not yet": "Todavía no",
"· date": "· fecha",
"Lane:": "Carril:",
"Level": "Nivel",
"Testing accommodations": "Adaptaciones para las pruebas",
"for the District Test Coordinator · from the Language Service Plan": "para el Coordinador de Pruebas del Distrito · del Plan de Servicios Lingüísticos",
"District Test Coordinator · date": "Coordinador de Pruebas del Distrito · fecha",
"EL teacher · date": "Maestro/a de EL · fecha",
"classroom — every teacher of record · chosen from each domain's level; gold edge = the builder's pick": "salón — todos los maestros del estudiante · elegidas según el nivel de cada dominio",
"one measurable goal each — suggest from the level, or choose from the ELPA21 goal bank (80 goals, each tied to an ELP Standard)": "una meta medible por dominio",
"Content graded for accuracy; language errors not penalized on non-ELA work": "Se califica el contenido; los errores de idioma no se penalizan fuera de la clase de inglés",
"Newcomer": "Recién llegado",
"Challenge": "Desafío",
"Identified in": "Identificado en",
"— Home Language Survey, screener and first notification are in the cumulative folder.": "— la Encuesta del idioma del hogar, la prueba inicial y la primera notificación están en el expediente.",
"Monitored former EL: no EL services. Classroom supports continue where a teacher sees a need; grades, attendance and assessments are checked every nine weeks (section 9). A student struggling for language reasons may re-enter with documented reasons and parent consent.": "Ex EL en seguimiento: sin servicios de EL. Los apoyos en el salón continúan donde el maestro vea la necesidad; las calificaciones, la asistencia y las evaluaciones se revisan cada nueve semanas (sección 9). Un estudiante con dificultades por razones de idioma puede reingresar con razones documentadas y el consentimiento de los padres.",
"(monitored: four years after exit, checked every nine weeks; re-entry requires documented reasons and parent consent)": "(en seguimiento: cuatro años después de salir, revisado cada nueve semanas; el reingreso requiere razones documentadas y consentimiento de los padres)",
"Immigrant (Title III)": "Inmigrante (Título III)",
"Long-term EL": "EL de largo plazo",
"_note": "Copia para la familia. Los encabezados y las opciones están en español; las metas, estrategias, evidencias y notas aparecen tal como las escribió el maestro, en inglés, y se explican con un intérprete. La versión en inglés es el registro oficial.",
},
};
