/* Languages for printing the Language Service Plan.

   Every fixed string on the form — headings, labels, the checkbox lists,
   the drop-down choices, the signature lines — in the family's language.
   What the teacher typed (goals, strategies, evidence, notes) stays as
   typed; the printed page says so and asks for an interpreter to walk the
   family through it.

   To add a language: copy the Spanish block, translate the right-hand
   side, keep ELPT / MAAP / MSIS / IEP / ELPA21 as they are, and add the
   code to LSP_LANG_NAMES. A key that is missing simply prints in English. */
window.LSP_LANG_NAMES = { en: "English", es: "Español", vi: "Tiếng Việt", ar: "العربية" };
window.LSP_LANG_RTL = { ar: true };
window.LSP_LANG = {
es: {
"Language Service Plan (LSP)": "Plan de Servicios Lingüísticos (LSP)",
"English Learner ·": "Aprendiz de inglés ·",
"· School year": "· Año escolar",
"Confidential · FERPA": "Confidencial · FERPA",
"1 · Student": "1 · Estudiante",
"2 · Identification trail": "2 · Identificación",
"3 · English proficiency": "3 · Dominio del inglés",
"4 · Program & services": "4 · Programa y servicios",
"5 · Instructional accommodations": "5 · Adaptaciones en el salón",
"6 · Assessment accommodations": "6 · Adaptaciones en las evaluaciones",
"7 · Grading, promotion & retention": "7 · Calificaciones, promoción y retención",
"8 · Goals by domain": "8 · Metas por dominio",
"9 · Status, monitoring & review": "9 · Estado, seguimiento y revisión",
"10 · Distribution & signatures": "10 · Distribución y firmas",
"Student is": "El/la estudiante es",
"New EL — identified this year": "Nuevo EL — identificado este año",
"Active EL — continuing": "EL activo — continúa",
"Monitored — Year 1 after exit": "En seguimiento — Año 1 después de salir",
"Monitored — Year 2": "En seguimiento — Año 2",
"Monitored — Year 3": "En seguimiento — Año 3",
"Monitored — Year 4": "En seguimiento — Año 4",
"Name": "Nombre",
"Student ID (MSIS)": "Número de estudiante (MSIS)",
"Grade": "Grado",
"School": "Escuela",
"Home language": "Idioma del hogar",
"Birth country": "País de nacimiento",
"First enrolled in U.S. schools": "Primera inscripción en escuelas de EE. UU.",
"Enrolled in this district": "Inscripción en este distrito",
"Years in EL program": "Años en el programa EL",
"0 (first year)": "0 (primer año)",
"Prior schooling": "Escolaridad previa",
"Continuous": "Continua",
"Interrupted / limited (SLIFE)": "Interrumpida / limitada (SLIFE)",
"Unknown — ask family": "Se desconoce — preguntar a la familia",
"IEP / 504": "IEP / 504",
"None": "Ninguno",
"IEP — see plan": "IEP — ver el plan",
"504 — see plan": "504 — ver el plan",
"Referral in progress": "Remisión en proceso",
"EL teacher of record (contact)": "Maestro/a de EL responsable (contacto)",
"Student Evaluation Team (EL committee)": "Equipo de Evaluación del Estudiante (comité EL)",
"— check each member; the signature block follows": "— marque cada integrante; las firmas siguen",
"EL teacher": "Maestro/a de EL",
"Classroom teacher(s)": "Maestro(s) de clase",
"Principal / designee": "Director/a o designado",
"Counselor": "Consejero/a",
"EL coordinator / Title III": "Coordinador/a de EL / Título III",
"Parent / guardian": "Padre, madre o tutor",
"Student": "Estudiante",
"Interpreter": "Intérprete",
"Special-education teacher": "Maestro/a de educación especial",
"required": "obligatorio",
"Home Language Survey → screener → parent notification, each dated": "Encuesta del idioma del hogar → prueba inicial → notificación a los padres, cada una con fecha",
"continuing EL — identification is on file from the first year; this year needs the annual notice and the parent's response": "EL que continúa — la identificación está archivada desde el primer año; este año requiere el aviso anual y la respuesta de los padres",
"Home Language Survey date": "Fecha de la Encuesta del idioma del hogar",
"Screener given": "Prueba inicial aplicada",
"ELPT Screener (ELPA21)": "Prueba inicial ELPT (ELPA21)",
"Screener date": "Fecha de la prueba inicial",
"Parent notification sent": "Notificación enviada a los padres",
"Notification language": "Idioma de la notificación",
"Interpreter for the conference": "Intérprete para la reunión",
"Yes — in person": "Sí — en persona",
"Yes — phone or video service": "Sí — por teléfono o video",
"Bilingual staff member": "Personal bilingüe",
"Not needed — parent proficient in English": "No necesario — el padre/madre domina el inglés",
"Offered and declined by parent": "Ofrecido y rechazado por el padre/madre",
"Not yet arranged": "Aún no se ha organizado",
"Annual notification (continuing ELs)": "Notificación anual (EL que continúan)",
"Parent response": "Respuesta de los padres",
"Accepted services": "Aceptó los servicios",
"Declined services (school still obligated)": "Rechazó los servicios (la escuela sigue obligada)",
"No response yet": "Sin respuesta todavía",
"most recent ELPT or screener, by domain": "ELPT o prueba inicial más reciente, por dominio",
"Listening": "Comprensión auditiva",
"Speaking": "Expresión oral",
"Reading": "Lectura",
"Writing": "Escritura",
"Overall determination": "Determinación general",
"Emerging": "Emergente",
"Progressing": "En progreso",
"Proficient": "Competente",
"Focus domain this year": "Dominio prioritario este año",
"Test / date": "Prueba / fecha",
"ELPT domain exemption": "Exención de un dominio del ELPT",
"None — all four domains": "Ninguna — los cuatro dominios",
"Listening (IEP)": "Comprensión auditiva (IEP)",
"Speaking (IEP)": "Expresión oral (IEP)",
"Reading (IEP)": "Lectura (IEP)",
"Writing (IEP)": "Escritura (IEP)",
"ELPT history": "Historial del ELPT",
"— every prior year the student has a score": "— cada año anterior con puntaje",
"Year": "Año",
"Overall": "General",
"Daily ESL/ELD class with a certified EL teacher": "Clase diaria de ESL/ELD con maestro/a de EL certificado",
"Co-teaching / push-in support in content classes": "Co-enseñanza / apoyo dentro de las clases de contenido",
"Pull-out small-group language instruction": "Instrucción de idioma en grupo pequeño fuera del salón",
"Sheltered content instruction (SIOP-style) in core classes": "Instrucción de contenido con apoyo lingüístico (estilo SIOP) en las materias básicas",
"Newcomer program / bridge (time-limited)": "Programa para recién llegados (por tiempo limitado)",
"Bilingual paraprofessional support": "Apoyo de un/a asistente bilingüe",
"Tutoring / after-school language support": "Tutoría / apoyo de idioma después de clases",
"Monitoring only (former EL)": "Solo seguimiento (ex EL)",
"EL instruction minutes per week": "Minutos de instrucción EL por semana",
"450 — one 90-minute block daily": "450 — un bloque de 90 minutos al día",
"250 — one 50-minute period daily": "250 — un periodo de 50 minutos al día",
"225 — 45 minutes daily": "225 — 45 minutos al día",
"150 — 30 minutes daily, pull-out": "150 — 30 minutos al día, fuera del salón",
"90 — co-teaching / push-in, 2 × 45": "90 — co-enseñanza, 2 × 45",
"0 — monitoring only (former EL)": "0 — solo seguimiento (ex EL)",
"Content classes with language support (list)": "Clases de contenido con apoyo de idioma (lista)",
"If dual-identified (IEP/504): how language and disability goals are coordinated": "Si tiene IEP/504: cómo se coordinan las metas de idioma y de discapacidad",
"If services declined: what continues anyway": "Si se rechazaron los servicios: lo que continúa de todos modos",
"Vocabulary preview before lessons": "Vocabulario anticipado antes de la lección",
"Sentence frames & word banks": "Marcos de oración y bancos de palabras",
"Visuals, realia & graphic organizers": "Imágenes, objetos reales y organizadores gráficos",
"Home-language support (bilingual peer, app for comprehension, bilingual notes)": "Apoyo en el idioma del hogar (compañero bilingüe, aplicación para comprender, notas bilingües)",
"Leveled / modified texts with grade-level vocabulary": "Textos nivelados o adaptados con vocabulario del grado",
"Reduced length or alternate response format": "Menor extensión o formato de respuesta alternativo",
"Oral or recorded responses accepted": "Se aceptan respuestas orales o grabadas",
"Directions repeated & clarified; comprehension checks": "Instrucciones repetidas y aclaradas; comprobación de comprensión",
"Extended wait time": "Tiempo de espera ampliado",
"Preferential seating": "Asiento preferencial",
"Content scored for accuracy; language errors not penalized on non-ELA work": "Se califica el contenido; los errores de idioma no se penalizan fuera de la clase de inglés",
"Bilingual dictionary in class": "Diccionario bilingüe en clase",
"classroom and state tests (MAAP, ELPT) — must match the Mississippi Testing Accommodations Manual and be used routinely in class": "pruebas del salón y del estado (MAAP, ELPT) — deben coincidir con el Manual de Adaptaciones de Mississippi y usarse de forma habitual en clase",
"Extended time (amount specified) — class & state (MTAM #20)": "Tiempo adicional (cantidad especificada) — salón y estado (MTAM #20)",
"Word-to-word bilingual glossary (print) — class & MAAP (MTAM #81; not allowed on ELPT)": "Glosario bilingüe palabra por palabra (impreso) — salón y MAAP (MTAM #81; no se permite en el ELPT)",
"Directions read aloud, repeated, clarified in English — class & state": "Instrucciones leídas en voz alta, repetidas y aclaradas en inglés — salón y estado",
"Test questions & answer choices read aloud / text-to-speech — class & MAAP (MTAM #55; passages not read; not ELPT Reading)": "Preguntas y opciones leídas en voz alta / texto a voz — salón y MAAP (MTAM #55; no se leen los pasajes; no en Lectura del ELPT)",
"Small-group administration — class & state": "Aplicación en grupo pequeño — salón y estado",
"Supervised breaks — class & state": "Descansos supervisados — salón y estado",
"Preferential seating — class & state": "Asiento preferencial — salón y estado",
"Classroom only: translated directions / home-language glossary (primary language not permitted on ELPT)": "Solo en el salón: instrucciones traducidas / glosario en el idioma del hogar (no se permite el idioma materno en el ELPT)",
"Classroom only: sentence frames / word bank on classroom tests": "Solo en el salón: marcos de oración / banco de palabras en las pruebas del salón",
"Classroom only: oral response on classroom tests": "Solo en el salón: respuesta oral en las pruebas del salón",
"Classroom only: reduced-length classroom tests": "Solo en el salón: pruebas del salón más cortas",
"State assessments this student takes this year": "Evaluaciones estatales que toma este año",
"— the accommodations above apply to each one checked": "— las adaptaciones de arriba se aplican a cada una marcada",
"ELPT (ELPA21) — listening, speaking, reading, writing": "ELPT (ELPA21) — comprensión auditiva, expresión oral, lectura, escritura",
"every EL, K–12, each spring until exit": "todo EL, K–12, cada primavera hasta salir del programa",
"Kindergarten Readiness Assessment — pre and post": "Evaluación de preparación para kínder — inicio y fin",
"K–3 universal reading screener": "Prueba universal de lectura K–3",
"K–3, three times a year": "K–3, tres veces al año",
"MAAP English Language Arts": "MAAP Lengua y Literatura en inglés",
"grades 3–8 · grade 3 is the reading gate (Literacy-Based Promotion Act)": "grados 3–8 · el grado 3 es la prueba de promoción en lectura",
"MAAP Mathematics": "MAAP Matemáticas",
"grades 3–8": "grados 3–8",
"MAAP Science": "MAAP Ciencias",
"grades 5 and 8": "grados 5 y 8",
"MAAP End-of-Course · English II": "MAAP Fin de curso · Inglés II",
"MAAP End-of-Course · Algebra I": "MAAP Fin de curso · Álgebra I",
"MAAP End-of-Course · Biology I": "MAAP Fin de curso · Biología I",
"MAAP End-of-Course · U.S. History": "MAAP Fin de curso · Historia de EE. UU.",
"when enrolled in the course": "cuando está inscrito en el curso",
"when enrolled — high school, or grade 8 if taking it early": "cuando está inscrito — preparatoria, o grado 8 si lo toma antes",
"ACT — state administration": "ACT — aplicación estatal",
"grade 11": "grado 11",
"ACT WorkKeys": "ACT WorkKeys",
"grade 11–12, career and technical pathways": "grados 11–12, programas técnicos y vocacionales",
"MAAP-A (alternate assessment)": "MAAP-A (evaluación alternativa)",
"IEP-team decision only · significant cognitive disability": "solo por decisión del equipo IEP · discapacidad cognitiva significativa",
"Notes for the District Test Coordinator": "Notas para el Coordinador de Pruebas del Distrito",
"First-year EL and the ELA state test": "EL de primer año y la prueba estatal de inglés",
"Not applicable — not in first 12 months": "No aplica — no está en los primeros 12 meses",
"DTC confirmed: takes ELA with accommodations": "Confirmado por el DTC: toma la prueba de inglés con adaptaciones",
"DTC confirmed: exempt from this year's ELA administration": "Confirmado por el DTC: exento de la prueba de inglés este año",
"Not yet confirmed with the DTC": "Aún no confirmado con el DTC",
"Report card / progress report notes that the student receives EL supports and accommodations": "La boleta / informe de progreso indica que el estudiante recibe apoyos y adaptaciones EL",
"Parents told, in a language they understand, what accommodations are used and how grades are earned": "Se informó a los padres, en un idioma que entienden, qué adaptaciones se usan y cómo se obtienen las calificaciones",
"Progress reports and report cards sent home translated or orally interpreted": "Informes de progreso y boletas enviados a casa traducidos o interpretados oralmente",
"Student is not retained solely because of English proficiency": "El estudiante no se retiene únicamente por su nivel de inglés",
"Promotion decisions consider ELPT growth and time in U.S. schools, not grade-level English alone": "La promoción considera el avance en el ELPT y el tiempo en escuelas de EE. UU., no solo el inglés del grado",
"Retention is under consideration for this student": "Se está considerando la retención de este estudiante",
"Interventions documented showing English is not the barrier — plus the parent meeting date and the parents' signed agreement": "Intervenciones documentadas que muestran que el inglés no es la barrera — más la fecha de la reunión con los padres y su acuerdo firmado",
"Strategies / who": "Estrategias / quién",
"— what is done, and by whom": "— qué se hace y quién lo hace",
"Evidence of progress": "Evidencia de progreso",
"— instrument, how often, where kept, what counts": "— instrumento, frecuencia, dónde se guarda, qué cuenta",
"Status (MSIS)": "Estado (MSIS)",
"Active EL": "EL activo",
"Active EL — parent declined services": "EL activo — los padres rechazaron los servicios",
"Monitored Year 1": "En seguimiento, año 1",
"Monitored Year 2": "En seguimiento, año 2",
"Monitored Year 3": "En seguimiento, año 3",
"Monitored Year 4": "En seguimiento, año 4",
"Exit criterion": "Criterio de salida",
"Level 4 or higher in each ELPT domain, same administration": "Nivel 4 o más en cada dominio del ELPT, en la misma aplicación",
"Plan written": "Plan redactado",
"Reviewed after ELPT results": "Revisado tras los resultados del ELPT",
"Nine-weeks reviews": "Revisiones cada nueve semanas",
"— grades, attendance, ELPT progress; teachers initial changes": "— calificaciones, asistencia, avance en el ELPT; los maestros firman los cambios",
"Q1 date · initials": "T1 fecha · iniciales",
"Q2 date · initials": "T2 fecha · iniciales",
"Q3 date · initials": "T3 fecha · iniciales",
"Q4 / end-of-year · initials": "T4 / fin de año · iniciales",
"Review notes / changes": "Notas de revisión / cambios",
"Teachers of record receiving this plan": "Maestros que reciben este plan",
"Given to teachers on": "Entregado a los maestros el",
"Copy to cumulative folder on": "Copia al expediente el",
"Translated / interpreted for parent": "Traducido / interpretado para los padres",
"Translated written copy given": "Se entregó copia escrita traducida",
"Interpreted orally at the conference": "Interpretado oralmente en la reunión",
"Both — translated copy and interpretation": "Ambos — copia traducida e interpretación",
"Not needed — parent reads English": "No necesario — el padre/madre lee inglés",
"Not yet": "Todavía no",
"· date": "· fecha",
"Lane:": "Carril:",
"Level": "Nivel",
"Testing accommodations": "Adaptaciones para las pruebas",
"for the District Test Coordinator · from the Language Service Plan": "para el Coordinador de Pruebas del Distrito · del Plan de Servicios Lingüísticos",
"District Test Coordinator · date": "Coordinador de Pruebas del Distrito · fecha",
"EL teacher · date": "Maestro/a de EL · fecha",
"classroom — every teacher of record · chosen from each domain's level; gold edge = the builder's pick": "salón — todos los maestros del estudiante · elegidas según el nivel de cada dominio",
"one measurable goal each — suggest from the level, or choose from the ELPA21 goal bank (80 goals, each tied to an ELP Standard)": "una meta medible por dominio",
"Content graded for accuracy; language errors not penalized on non-ELA work": "Se califica el contenido; los errores de idioma no se penalizan fuera de la clase de inglés",
"Newcomer": "Recién llegado",
"Challenge": "Desafío",
"Identified in": "Identificado en",
"— Home Language Survey, screener and first notification are in the cumulative folder.": "— la Encuesta del idioma del hogar, la prueba inicial y la primera notificación están en el expediente.",
"Monitored former EL: no EL services. Classroom supports continue where a teacher sees a need; grades, attendance and assessments are checked every nine weeks (section 9). A student struggling for language reasons may re-enter with documented reasons and parent consent.": "Ex EL en seguimiento: sin servicios de EL. Los apoyos en el salón continúan donde el maestro vea la necesidad; las calificaciones, la asistencia y las evaluaciones se revisan cada nueve semanas (sección 9). Un estudiante con dificultades por razones de idioma puede reingresar con razones documentadas y el consentimiento de los padres.",
"(monitored: four years after exit, checked every nine weeks; re-entry requires documented reasons and parent consent)": "(en seguimiento: cuatro años después de salir, revisado cada nueve semanas; el reingreso requiere razones documentadas y consentimiento de los padres)",
"Immigrant (Title III)": "Inmigrante (Título III)",
"Long-term EL": "EL de largo plazo",
"_note": "Copia para la familia. Los encabezados y las opciones están en español; las metas, estrategias, evidencias y notas aparecen tal como las escribió el maestro, en inglés, y se explican con un intérprete. La versión en inglés es el registro oficial.",
},
vi: {
"Language Service Plan (LSP)": "Kế hoạch Dịch vụ Ngôn ngữ (LSP)",
"English Learner ·": "Học sinh học tiếng Anh ·",
"· School year": "· Năm học",
"Confidential · FERPA": "Bảo mật · FERPA",
"1 · Student": "1 · Học sinh",
"2 · Identification trail": "2 · Quá trình xác định",
"3 · English proficiency": "3 · Trình độ tiếng Anh",
"4 · Program & services": "4 · Chương trình và dịch vụ",
"5 · Instructional accommodations": "5 · Hỗ trợ trong lớp học",
"6 · Assessment accommodations": "6 · Hỗ trợ khi kiểm tra",
"7 · Grading, promotion & retention": "7 · Chấm điểm, lên lớp và ở lại lớp",
"8 · Goals by domain": "8 · Mục tiêu theo từng kỹ năng",
"9 · Status, monitoring & review": "9 · Tình trạng, theo dõi và xem xét",
"10 · Distribution & signatures": "10 · Phân phối và chữ ký",
"Student is": "Học sinh là",
"New EL — identified this year": "EL mới — được xác định năm nay",
"Active EL — continuing": "EL đang học — tiếp tục",
"Monitored — Year 1 after exit": "Theo dõi — Năm 1 sau khi ra khỏi chương trình",
"Monitored — Year 2": "Theo dõi — Năm 2",
"Monitored — Year 3": "Theo dõi — Năm 3",
"Monitored — Year 4": "Theo dõi — Năm 4",
"Name": "Họ và tên",
"Student ID (MSIS)": "Mã số học sinh (MSIS)",
"Grade": "Lớp",
"School": "Trường",
"Home language": "Ngôn ngữ ở nhà",
"Birth country": "Nước sinh",
"First enrolled in U.S. schools": "Lần đầu nhập học tại trường ở Hoa Kỳ",
"Enrolled in this district": "Nhập học tại học khu này",
"Years in EL program": "Số năm trong chương trình EL",
"0 (first year)": "0 (năm đầu)",
"Prior schooling": "Việc học trước đây",
"Continuous": "Liên tục",
"Interrupted / limited (SLIFE)": "Gián đoạn / hạn chế (SLIFE)",
"Unknown — ask family": "Chưa rõ — hỏi gia đình",
"IEP / 504": "IEP / 504",
"None": "Không có",
"IEP — see plan": "IEP — xem kế hoạch",
"504 — see plan": "504 — xem kế hoạch",
"Referral in progress": "Đang trong quá trình giới thiệu",
"EL teacher of record (contact)": "Giáo viên EL phụ trách (liên hệ)",
"Student Evaluation Team (EL committee)": "Nhóm Đánh giá Học sinh (ủy ban EL)",
"— check each member; the signature block follows": "— đánh dấu từng thành viên; phần chữ ký ở sau",
"EL teacher": "Giáo viên EL",
"Classroom teacher(s)": "Giáo viên đứng lớp",
"Principal / designee": "Hiệu trưởng / người được ủy quyền",
"Counselor": "Cố vấn học đường",
"EL coordinator / Title III": "Điều phối viên EL / Title III",
"Parent / guardian": "Phụ huynh / người giám hộ",
"Student": "Học sinh",
"Interpreter": "Thông dịch viên",
"Special-education teacher": "Giáo viên giáo dục đặc biệt",
"required": "bắt buộc",
"Home Language Survey → screener → parent notification, each dated": "Khảo sát ngôn ngữ ở nhà → bài kiểm tra sàng lọc → thông báo cho phụ huynh, mỗi mục có ghi ngày",
"continuing EL — identification is on file from the first year; this year needs the annual notice and the parent's response": "EL tiếp tục — hồ sơ xác định đã lưu từ năm đầu; năm nay cần thông báo hằng năm và phản hồi của phụ huynh",
"Home Language Survey date": "Ngày Khảo sát ngôn ngữ ở nhà",
"Screener given": "Bài kiểm tra sàng lọc đã làm",
"ELPT Screener (ELPA21)": "Bài sàng lọc ELPT (ELPA21)",
"Screener date": "Ngày kiểm tra sàng lọc",
"Parent notification sent": "Đã gửi thông báo cho phụ huynh",
"Notification language": "Ngôn ngữ của thông báo",
"Interpreter for the conference": "Thông dịch viên cho buổi họp",
"Yes — in person": "Có — trực tiếp",
"Yes — phone or video service": "Có — qua điện thoại hoặc video",
"Bilingual staff member": "Nhân viên song ngữ",
"Not needed — parent proficient in English": "Không cần — phụ huynh thông thạo tiếng Anh",
"Offered and declined by parent": "Đã đề nghị và phụ huynh từ chối",
"Not yet arranged": "Chưa sắp xếp",
"Annual notification (continuing ELs)": "Thông báo hằng năm (EL tiếp tục)",
"Parent response": "Phản hồi của phụ huynh",
"Accepted services": "Đồng ý nhận dịch vụ",
"Declined services (school still obligated)": "Từ chối dịch vụ (nhà trường vẫn có trách nhiệm)",
"No response yet": "Chưa có phản hồi",
"most recent ELPT or screener, by domain": "ELPT hoặc bài sàng lọc gần nhất, theo kỹ năng",
"Listening": "Nghe",
"Speaking": "Nói",
"Reading": "Đọc",
"Writing": "Viết",
"Overall determination": "Kết luận chung",
"Emerging": "Mới bắt đầu",
"Progressing": "Đang tiến bộ",
"Proficient": "Thông thạo",
"Focus domain this year": "Kỹ năng trọng tâm năm nay",
"Test / date": "Bài kiểm tra / ngày",
"ELPT domain exemption": "Miễn một kỹ năng của ELPT",
"None — all four domains": "Không — cả bốn kỹ năng",
"Listening (IEP)": "Nghe (IEP)",
"Speaking (IEP)": "Nói (IEP)",
"Reading (IEP)": "Đọc (IEP)",
"Writing (IEP)": "Viết (IEP)",
"ELPT history": "Lịch sử ELPT",
"— every prior year the student has a score": "— mỗi năm trước có điểm",
"Year": "Năm",
"Overall": "Chung",
"Daily ESL/ELD class with a certified EL teacher": "Lớp ESL/ELD hằng ngày với giáo viên EL có chứng nhận",
"Co-teaching / push-in support in content classes": "Đồng giảng dạy / hỗ trợ trong lớp môn học",
"Pull-out small-group language instruction": "Dạy ngôn ngữ theo nhóm nhỏ ngoài lớp",
"Sheltered content instruction (SIOP-style) in core classes": "Dạy môn học có hỗ trợ ngôn ngữ (kiểu SIOP) ở các môn chính",
"Newcomer program / bridge (time-limited)": "Chương trình cho học sinh mới đến (có thời hạn)",
"Bilingual paraprofessional support": "Hỗ trợ của trợ giảng song ngữ",
"Tutoring / after-school language support": "Phụ đạo / hỗ trợ ngôn ngữ sau giờ học",
"Monitoring only (former EL)": "Chỉ theo dõi (EL cũ)",
"EL instruction minutes per week": "Số phút học EL mỗi tuần",
"450 — one 90-minute block daily": "450 — một tiết 90 phút mỗi ngày",
"250 — one 50-minute period daily": "250 — một tiết 50 phút mỗi ngày",
"225 — 45 minutes daily": "225 — 45 phút mỗi ngày",
"150 — 30 minutes daily, pull-out": "150 — 30 phút mỗi ngày, ngoài lớp",
"90 — co-teaching / push-in, 2 × 45": "90 — đồng giảng dạy, 2 × 45",
"0 — monitoring only (former EL)": "0 — chỉ theo dõi (EL cũ)",
"Content classes with language support (list)": "Các lớp môn học có hỗ trợ ngôn ngữ (liệt kê)",
"If dual-identified (IEP/504): how language and disability goals are coordinated": "Nếu có IEP/504: cách phối hợp mục tiêu ngôn ngữ và mục tiêu khuyết tật",
"If services declined: what continues anyway": "Nếu từ chối dịch vụ: những gì vẫn tiếp tục",
"Vocabulary preview before lessons": "Giới thiệu từ vựng trước bài học",
"Sentence frames & word banks": "Khung câu và ngân hàng từ",
"Visuals, realia & graphic organizers": "Hình ảnh, vật thật và sơ đồ tổ chức",
"Home-language support (bilingual peer, app for comprehension, bilingual notes)": "Hỗ trợ bằng ngôn ngữ ở nhà (bạn song ngữ, ứng dụng hỗ trợ hiểu bài, ghi chú song ngữ)",
"Leveled / modified texts with grade-level vocabulary": "Văn bản theo trình độ / điều chỉnh với từ vựng của lớp",
"Reduced length or alternate response format": "Rút ngắn độ dài hoặc hình thức trả lời khác",
"Oral or recorded responses accepted": "Chấp nhận trả lời bằng lời hoặc ghi âm",
"Directions repeated & clarified; comprehension checks": "Nhắc lại và làm rõ hướng dẫn; kiểm tra mức độ hiểu",
"Extended wait time": "Thêm thời gian chờ",
"Preferential seating": "Chỗ ngồi ưu tiên",
"Content scored for accuracy; language errors not penalized on non-ELA work": "Chấm điểm nội dung; không trừ điểm lỗi ngôn ngữ ngoài môn tiếng Anh",
"Bilingual dictionary in class": "Từ điển song ngữ trong lớp",
"classroom and state tests (MAAP, ELPT) — must match the Mississippi Testing Accommodations Manual and be used routinely in class": "bài kiểm tra trong lớp và của tiểu bang (MAAP, ELPT) — phải đúng theo Sổ tay Hỗ trợ Kiểm tra Mississippi và được dùng thường xuyên trong lớp",
"Extended time (amount specified) — class & state (MTAM #20)": "Thêm thời gian (ghi rõ bao nhiêu) — lớp và tiểu bang (MTAM #20)",
"Word-to-word bilingual glossary (print) — class & MAAP (MTAM #81; not allowed on ELPT)": "Bảng từ song ngữ từng từ (bản in) — lớp và MAAP (MTAM #81; không được dùng trong ELPT)",
"Directions read aloud, repeated, clarified in English — class & state": "Đọc to, nhắc lại và làm rõ hướng dẫn bằng tiếng Anh — lớp và tiểu bang",
"Test questions & answer choices read aloud / text-to-speech — class & MAAP (MTAM #55; passages not read; not ELPT Reading)": "Đọc to câu hỏi và các lựa chọn / chuyển văn bản thành giọng nói — lớp và MAAP (MTAM #55; không đọc đoạn văn; không áp dụng cho phần Đọc của ELPT)",
"Small-group administration — class & state": "Làm bài theo nhóm nhỏ — lớp và tiểu bang",
"Supervised breaks — class & state": "Nghỉ giải lao có giám sát — lớp và tiểu bang",
"Preferential seating — class & state": "Chỗ ngồi ưu tiên — lớp và tiểu bang",
"Classroom only: translated directions / home-language glossary (primary language not permitted on ELPT)": "Chỉ trong lớp: hướng dẫn được dịch / bảng từ bằng ngôn ngữ ở nhà (không được dùng tiếng mẹ đẻ trong ELPT)",
"Classroom only: sentence frames / word bank on classroom tests": "Chỉ trong lớp: khung câu / ngân hàng từ trong bài kiểm tra ở lớp",
"Classroom only: oral response on classroom tests": "Chỉ trong lớp: trả lời bằng lời trong bài kiểm tra ở lớp",
"Classroom only: reduced-length classroom tests": "Chỉ trong lớp: bài kiểm tra ở lớp rút ngắn",
"State assessments this student takes this year": "Các kỳ thi tiểu bang học sinh tham gia năm nay",
"— the accommodations above apply to each one checked": "— các hỗ trợ ở trên áp dụng cho mỗi kỳ thi được đánh dấu",
"ELPT (ELPA21) — listening, speaking, reading, writing": "ELPT (ELPA21) — nghe, nói, đọc, viết",
"every EL, K–12, each spring until exit": "mọi EL, K–12, mỗi mùa xuân cho đến khi ra khỏi chương trình",
"Kindergarten Readiness Assessment — pre and post": "Đánh giá sẵn sàng vào mẫu giáo — đầu và cuối năm",
"K–3 universal reading screener": "Bài sàng lọc đọc toàn diện K–3",
"K–3, three times a year": "K–3, ba lần mỗi năm",
"MAAP English Language Arts": "MAAP Ngữ văn tiếng Anh",
"grades 3–8 · grade 3 is the reading gate (Literacy-Based Promotion Act)": "lớp 3–8 · lớp 3 là kỳ thi đọc để lên lớp",
"MAAP Mathematics": "MAAP Toán",
"grades 3–8": "lớp 3–8",
"MAAP Science": "MAAP Khoa học",
"grades 5 and 8": "lớp 5 và 8",
"MAAP End-of-Course · English II": "MAAP Cuối khóa · Tiếng Anh II",
"MAAP End-of-Course · Algebra I": "MAAP Cuối khóa · Đại số I",
"MAAP End-of-Course · Biology I": "MAAP Cuối khóa · Sinh học I",
"MAAP End-of-Course · U.S. History": "MAAP Cuối khóa · Lịch sử Hoa Kỳ",
"when enrolled in the course": "khi đang học môn này",
"when enrolled — high school, or grade 8 if taking it early": "khi đang học — trung học, hoặc lớp 8 nếu học sớm",
"ACT — state administration": "ACT — do tiểu bang tổ chức",
"grade 11": "lớp 11",
"ACT WorkKeys": "ACT WorkKeys",
"grade 11–12, career and technical pathways": "lớp 11–12, chương trình hướng nghiệp và kỹ thuật",
"MAAP-A (alternate assessment)": "MAAP-A (đánh giá thay thế)",
"IEP-team decision only · significant cognitive disability": "chỉ do nhóm IEP quyết định · khuyết tật nhận thức nghiêm trọng",
"Notes for the District Test Coordinator": "Ghi chú cho Điều phối viên Kiểm tra Học khu",
"First-year EL and the ELA state test": "EL năm đầu và kỳ thi tiếng Anh của tiểu bang",
"Not applicable — not in first 12 months": "Không áp dụng — không trong 12 tháng đầu",
"DTC confirmed: takes ELA with accommodations": "DTC xác nhận: thi tiếng Anh có hỗ trợ",
"DTC confirmed: exempt from this year's ELA administration": "DTC xác nhận: được miễn kỳ thi tiếng Anh năm nay",
"Not yet confirmed with the DTC": "Chưa xác nhận với DTC",
"Report card / progress report notes that the student receives EL supports and accommodations": "Phiếu điểm / báo cáo tiến bộ ghi rõ học sinh nhận hỗ trợ EL",
"Parents told, in a language they understand, what accommodations are used and how grades are earned": "Phụ huynh được thông báo, bằng ngôn ngữ họ hiểu, về các hỗ trợ được dùng và cách tính điểm",
"Progress reports and report cards sent home translated or orally interpreted": "Báo cáo tiến bộ và phiếu điểm gửi về nhà được dịch hoặc thông dịch",
"Student is not retained solely because of English proficiency": "Học sinh không bị ở lại lớp chỉ vì trình độ tiếng Anh",
"Promotion decisions consider ELPT growth and time in U.S. schools, not grade-level English alone": "Quyết định lên lớp xét đến tiến bộ ELPT và thời gian học ở Hoa Kỳ, không chỉ tiếng Anh theo lớp",
"Retention is under consideration for this student": "Đang cân nhắc cho học sinh này ở lại lớp",
"Interventions documented showing English is not the barrier — plus the parent meeting date and the parents' signed agreement": "Các biện pháp can thiệp đã ghi nhận cho thấy tiếng Anh không phải là rào cản — cùng ngày họp phụ huynh và văn bản đồng ý có chữ ký của phụ huynh",
"Strategies / who": "Chiến lược / ai thực hiện",
"— what is done, and by whom": "— làm gì và ai làm",
"Evidence of progress": "Bằng chứng tiến bộ",
"— instrument, how often, where kept, what counts": "— công cụ, tần suất, lưu ở đâu, tính thế nào",
"Status (MSIS)": "Tình trạng (MSIS)",
"Active EL": "EL đang học",
"Active EL — parent declined services": "EL đang học — phụ huynh từ chối dịch vụ",
"Monitored Year 1": "Theo dõi năm 1",
"Monitored Year 2": "Theo dõi năm 2",
"Monitored Year 3": "Theo dõi năm 3",
"Monitored Year 4": "Theo dõi năm 4",
"Exit criterion": "Tiêu chí ra khỏi chương trình",
"Level 4 or higher in each ELPT domain, same administration": "Mức 4 trở lên ở mỗi kỹ năng ELPT, trong cùng một kỳ thi",
"Plan written": "Ngày lập kế hoạch",
"Reviewed after ELPT results": "Xem xét sau khi có kết quả ELPT",
"Nine-weeks reviews": "Xem xét mỗi chín tuần",
"— grades, attendance, ELPT progress; teachers initial changes": "— điểm số, chuyên cần, tiến bộ ELPT; giáo viên ký tắt các thay đổi",
"Q1 date · initials": "Quý 1 ngày · ký tắt",
"Q2 date · initials": "Quý 2 ngày · ký tắt",
"Q3 date · initials": "Quý 3 ngày · ký tắt",
"Q4 / end-of-year · initials": "Quý 4 / cuối năm · ký tắt",
"Review notes / changes": "Ghi chú xem xét / thay đổi",
"Teachers of record receiving this plan": "Các giáo viên nhận kế hoạch này",
"Given to teachers on": "Giao cho giáo viên ngày",
"Copy to cumulative folder on": "Lưu bản sao vào hồ sơ ngày",
"Translated / interpreted for parent": "Đã dịch / thông dịch cho phụ huynh",
"Translated written copy given": "Đã giao bản dịch viết",
"Interpreted orally at the conference": "Đã thông dịch trong buổi họp",
"Both — translated copy and interpretation": "Cả hai — bản dịch và thông dịch",
"Not needed — parent reads English": "Không cần — phụ huynh đọc được tiếng Anh",
"Not yet": "Chưa",
"· date": "· ngày",
"Lane:": "Nhóm:",
"Level": "Mức",
"Testing accommodations": "Hỗ trợ khi kiểm tra",
"for the District Test Coordinator · from the Language Service Plan": "cho Điều phối viên Kiểm tra Học khu · từ Kế hoạch Dịch vụ Ngôn ngữ",
"District Test Coordinator · date": "Điều phối viên Kiểm tra Học khu · ngày",
"EL teacher · date": "Giáo viên EL · ngày",
"classroom — every teacher of record · chosen from each domain's level; gold edge = the builder's pick": "trong lớp — mọi giáo viên của học sinh · chọn theo mức của từng kỹ năng",
"one measurable goal each — suggest from the level, or choose from the ELPA21 goal bank (80 goals, each tied to an ELP Standard)": "một mục tiêu đo lường được cho mỗi kỹ năng",
"Content graded for accuracy; language errors not penalized on non-ELA work": "Chấm điểm nội dung; không trừ điểm lỗi ngôn ngữ ngoài môn tiếng Anh",
"Newcomer": "Mới đến",
"Challenge": "Thử thách",
"Identified in": "Được xác định năm",
"— Home Language Survey, screener and first notification are in the cumulative folder.": "— Khảo sát ngôn ngữ ở nhà, bài sàng lọc và thông báo đầu tiên đã lưu trong hồ sơ.",
"Monitored former EL: no EL services. Classroom supports continue where a teacher sees a need; grades, attendance and assessments are checked every nine weeks (section 9). A student struggling for language reasons may re-enter with documented reasons and parent consent.": "EL cũ đang được theo dõi: không có dịch vụ EL. Hỗ trợ trong lớp tiếp tục khi giáo viên thấy cần; điểm số, chuyên cần và bài kiểm tra được xem xét mỗi chín tuần (mục 9). Học sinh gặp khó khăn vì lý do ngôn ngữ có thể vào lại chương trình với lý do được ghi nhận và sự đồng ý của phụ huynh.",
"(monitored: four years after exit, checked every nine weeks; re-entry requires documented reasons and parent consent)": "(theo dõi: bốn năm sau khi ra khỏi chương trình, xem xét mỗi chín tuần; vào lại cần lý do được ghi nhận và sự đồng ý của phụ huynh)",
"Immigrant (Title III)": "Nhập cư (Title III)",
"Long-term EL": "EL lâu năm",
"_note": "Bản dành cho gia đình. Các tiêu đề và lựa chọn bằng tiếng Việt; mục tiêu, chiến lược, bằng chứng và ghi chú giữ nguyên như giáo viên viết bằng tiếng Anh và sẽ được giải thích qua thông dịch viên. Bản tiếng Anh là hồ sơ chính thức.",
},
ar: {
"Language Service Plan (LSP)": "خطة الخدمات اللغوية (LSP)",
"English Learner ·": "متعلّم اللغة الإنجليزية ·",
"· School year": "· العام الدراسي",
"Confidential · FERPA": "سرّي · FERPA",
"1 · Student": "1 · الطالب",
"2 · Identification trail": "2 · مسار التحديد",
"3 · English proficiency": "3 · مستوى إتقان الإنجليزية",
"4 · Program & services": "4 · البرنامج والخدمات",
"5 · Instructional accommodations": "5 · التسهيلات داخل الصف",
"6 · Assessment accommodations": "6 · التسهيلات في الاختبارات",
"7 · Grading, promotion & retention": "7 · الدرجات والترفيع والإعادة",
"8 · Goals by domain": "8 · الأهداف حسب المهارة",
"9 · Status, monitoring & review": "9 · الحالة والمتابعة والمراجعة",
"10 · Distribution & signatures": "10 · التوزيع والتوقيعات",
"Student is": "الطالب",
"New EL — identified this year": "متعلّم جديد — تم تحديده هذا العام",
"Active EL — continuing": "متعلّم نشط — مستمر",
"Monitored — Year 1 after exit": "تحت المتابعة — السنة 1 بعد الخروج",
"Monitored — Year 2": "تحت المتابعة — السنة 2",
"Monitored — Year 3": "تحت المتابعة — السنة 3",
"Monitored — Year 4": "تحت المتابعة — السنة 4",
"Name": "الاسم",
"Student ID (MSIS)": "رقم الطالب (MSIS)",
"Grade": "الصف",
"School": "المدرسة",
"Home language": "لغة المنزل",
"Birth country": "بلد الولادة",
"First enrolled in U.S. schools": "أول التحاق بمدارس الولايات المتحدة",
"Enrolled in this district": "الالتحاق بهذه المنطقة التعليمية",
"Years in EL program": "سنوات في برنامج EL",
"0 (first year)": "0 (السنة الأولى)",
"Prior schooling": "التعليم السابق",
"Continuous": "متواصل",
"Interrupted / limited (SLIFE)": "متقطّع / محدود (SLIFE)",
"Unknown — ask family": "غير معروف — اسأل الأسرة",
"IEP / 504": "IEP / 504",
"None": "لا يوجد",
"IEP — see plan": "IEP — انظر الخطة",
"504 — see plan": "504 — انظر الخطة",
"Referral in progress": "الإحالة قيد الإجراء",
"EL teacher of record (contact)": "معلّم EL المسؤول (جهة الاتصال)",
"Student Evaluation Team (EL committee)": "فريق تقييم الطالب (لجنة EL)",
"— check each member; the signature block follows": "— ضع علامة على كل عضو؛ التوقيعات تأتي بعد ذلك",
"EL teacher": "معلّم EL",
"Classroom teacher(s)": "معلّم/معلّمو الصف",
"Principal / designee": "المدير / من ينوب عنه",
"Counselor": "المرشد",
"EL coordinator / Title III": "منسّق EL / Title III",
"Parent / guardian": "ولي الأمر",
"Student": "الطالب",
"Interpreter": "المترجم الشفوي",
"Special-education teacher": "معلّم التربية الخاصة",
"required": "مطلوب",
"Home Language Survey → screener → parent notification, each dated": "استبيان لغة المنزل ← اختبار الفرز ← إشعار ولي الأمر، كلٌّ بتاريخه",
"continuing EL — identification is on file from the first year; this year needs the annual notice and the parent's response": "متعلّم مستمر — التحديد محفوظ في الملف منذ السنة الأولى؛ هذا العام يحتاج الإشعار السنوي وردّ ولي الأمر",
"Home Language Survey date": "تاريخ استبيان لغة المنزل",
"Screener given": "اختبار الفرز المُجرى",
"ELPT Screener (ELPA21)": "اختبار الفرز ELPT (ELPA21)",
"Screener date": "تاريخ اختبار الفرز",
"Parent notification sent": "تاريخ إرسال إشعار ولي الأمر",
"Notification language": "لغة الإشعار",
"Interpreter for the conference": "مترجم شفوي للاجتماع",
"Yes — in person": "نعم — حضوريًا",
"Yes — phone or video service": "نعم — عبر الهاتف أو الفيديو",
"Bilingual staff member": "موظّف ثنائي اللغة",
"Not needed — parent proficient in English": "غير مطلوب — ولي الأمر يتقن الإنجليزية",
"Offered and declined by parent": "عُرض ورفضه ولي الأمر",
"Not yet arranged": "لم يُرتَّب بعد",
"Annual notification (continuing ELs)": "الإشعار السنوي (للمتعلّمين المستمرين)",
"Parent response": "ردّ ولي الأمر",
"Accepted services": "قبِل الخدمات",
"Declined services (school still obligated)": "رفض الخدمات (المدرسة تبقى ملزمة)",
"No response yet": "لا ردّ بعد",
"most recent ELPT or screener, by domain": "أحدث ELPT أو اختبار فرز، حسب المهارة",
"Listening": "الاستماع",
"Speaking": "التحدّث",
"Reading": "القراءة",
"Writing": "الكتابة",
"Overall determination": "التقدير العام",
"Emerging": "ناشئ",
"Progressing": "متقدّم",
"Proficient": "متقن",
"Focus domain this year": "مهارة التركيز هذا العام",
"Test / date": "الاختبار / التاريخ",
"ELPT domain exemption": "إعفاء من إحدى مهارات ELPT",
"None — all four domains": "لا يوجد — المهارات الأربع كلها",
"Listening (IEP)": "الاستماع (IEP)",
"Speaking (IEP)": "التحدّث (IEP)",
"Reading (IEP)": "القراءة (IEP)",
"Writing (IEP)": "الكتابة (IEP)",
"ELPT history": "سجلّ ELPT",
"— every prior year the student has a score": "— كل سنة سابقة للطالب فيها درجة",
"Year": "السنة",
"Overall": "العام",
"Daily ESL/ELD class with a certified EL teacher": "حصة ESL/ELD يومية مع معلّم EL معتمد",
"Co-teaching / push-in support in content classes": "تدريس مشترك / دعم داخل حصص المواد",
"Pull-out small-group language instruction": "تعليم لغوي في مجموعة صغيرة خارج الصف",
"Sheltered content instruction (SIOP-style) in core classes": "تدريس المواد بدعم لغوي (على نمط SIOP) في المواد الأساسية",
"Newcomer program / bridge (time-limited)": "برنامج القادمين الجدد (محدود المدة)",
"Bilingual paraprofessional support": "دعم مساعد تعليمي ثنائي اللغة",
"Tutoring / after-school language support": "دروس تقوية / دعم لغوي بعد الدوام",
"Monitoring only (former EL)": "متابعة فقط (متعلّم سابق)",
"EL instruction minutes per week": "دقائق تعليم EL أسبوعيًا",
"450 — one 90-minute block daily": "450 — حصة 90 دقيقة يوميًا",
"250 — one 50-minute period daily": "250 — حصة 50 دقيقة يوميًا",
"225 — 45 minutes daily": "225 — 45 دقيقة يوميًا",
"150 — 30 minutes daily, pull-out": "150 — 30 دقيقة يوميًا، خارج الصف",
"90 — co-teaching / push-in, 2 × 45": "90 — تدريس مشترك، 2 × 45",
"0 — monitoring only (former EL)": "0 — متابعة فقط (متعلّم سابق)",
"Content classes with language support (list)": "حصص المواد ذات الدعم اللغوي (اذكرها)",
"If dual-identified (IEP/504): how language and disability goals are coordinated": "إذا كان لديه IEP/504: كيف تُنسَّق أهداف اللغة وأهداف الإعاقة",
"If services declined: what continues anyway": "إذا رُفضت الخدمات: ما الذي يستمر رغم ذلك",
"Vocabulary preview before lessons": "تقديم المفردات قبل الدرس",
"Sentence frames & word banks": "قوالب الجمل وبنوك الكلمات",
"Visuals, realia & graphic organizers": "الصور والأشياء الحقيقية والمنظّمات البيانية",
"Home-language support (bilingual peer, app for comprehension, bilingual notes)": "دعم بلغة المنزل (زميل ثنائي اللغة، تطبيق للفهم، ملاحظات ثنائية اللغة)",
"Leveled / modified texts with grade-level vocabulary": "نصوص مستوياتية / معدّلة بمفردات الصف",
"Reduced length or alternate response format": "تقليل الطول أو صيغة إجابة بديلة",
"Oral or recorded responses accepted": "تُقبل الإجابات الشفوية أو المسجّلة",
"Directions repeated & clarified; comprehension checks": "تكرار التعليمات وتوضيحها؛ التحقق من الفهم",
"Extended wait time": "وقت انتظار إضافي",
"Preferential seating": "مقعد مفضّل",
"Content scored for accuracy; language errors not penalized on non-ELA work": "تُقيَّم صحة المحتوى؛ لا تُخصم أخطاء اللغة خارج مادة اللغة الإنجليزية",
"Bilingual dictionary in class": "قاموس ثنائي اللغة في الصف",
"classroom and state tests (MAAP, ELPT) — must match the Mississippi Testing Accommodations Manual and be used routinely in class": "اختبارات الصف والولاية (MAAP، ELPT) — يجب أن تطابق دليل تسهيلات الاختبار في ميسيسيبي وأن تُستخدم بانتظام في الصف",
"Extended time (amount specified) — class & state (MTAM #20)": "وقت إضافي (بمقدار محدد) — الصف والولاية (MTAM #20)",
"Word-to-word bilingual glossary (print) — class & MAAP (MTAM #81; not allowed on ELPT)": "مسرد ثنائي اللغة كلمة بكلمة (مطبوع) — الصف وMAAP (MTAM #81؛ غير مسموح في ELPT)",
"Directions read aloud, repeated, clarified in English — class & state": "قراءة التعليمات بصوت عالٍ وتكرارها وتوضيحها بالإنجليزية — الصف والولاية",
"Test questions & answer choices read aloud / text-to-speech — class & MAAP (MTAM #55; passages not read; not ELPT Reading)": "قراءة الأسئلة والخيارات بصوت عالٍ / تحويل النص إلى كلام — الصف وMAAP (MTAM #55؛ لا تُقرأ النصوص؛ لا ينطبق على قراءة ELPT)",
"Small-group administration — class & state": "أداء الاختبار في مجموعة صغيرة — الصف والولاية",
"Supervised breaks — class & state": "فترات راحة تحت الإشراف — الصف والولاية",
"Preferential seating — class & state": "مقعد مفضّل — الصف والولاية",
"Classroom only: translated directions / home-language glossary (primary language not permitted on ELPT)": "في الصف فقط: تعليمات مترجمة / مسرد بلغة المنزل (اللغة الأم غير مسموح بها في ELPT)",
"Classroom only: sentence frames / word bank on classroom tests": "في الصف فقط: قوالب الجمل / بنك الكلمات في اختبارات الصف",
"Classroom only: oral response on classroom tests": "في الصف فقط: إجابة شفوية في اختبارات الصف",
"Classroom only: reduced-length classroom tests": "في الصف فقط: اختبارات صفّية مختصرة",
"State assessments this student takes this year": "اختبارات الولاية التي يؤديها الطالب هذا العام",
"— the accommodations above apply to each one checked": "— التسهيلات أعلاه تنطبق على كل اختبار مُعلَّم",
"ELPT (ELPA21) — listening, speaking, reading, writing": "ELPT (ELPA21) — الاستماع والتحدّث والقراءة والكتابة",
"every EL, K–12, each spring until exit": "كل متعلّم، من الروضة حتى الصف 12، كل ربيع حتى الخروج",
"Kindergarten Readiness Assessment — pre and post": "تقييم الجاهزية لرياض الأطفال — قبلي وبعدي",
"K–3 universal reading screener": "اختبار فرز القراءة الشامل K–3",
"K–3, three times a year": "K–3، ثلاث مرات في السنة",
"MAAP English Language Arts": "MAAP اللغة الإنجليزية وآدابها",
"grades 3–8 · grade 3 is the reading gate (Literacy-Based Promotion Act)": "الصفوف 3–8 · الصف 3 هو اختبار القراءة للترفيع",
"MAAP Mathematics": "MAAP الرياضيات",
"grades 3–8": "الصفوف 3–8",
"MAAP Science": "MAAP العلوم",
"grades 5 and 8": "الصفان 5 و8",
"MAAP End-of-Course · English II": "MAAP نهاية المقرر · الإنجليزية II",
"MAAP End-of-Course · Algebra I": "MAAP نهاية المقرر · الجبر I",
"MAAP End-of-Course · Biology I": "MAAP نهاية المقرر · الأحياء I",
"MAAP End-of-Course · U.S. History": "MAAP نهاية المقرر · تاريخ الولايات المتحدة",
"when enrolled in the course": "عند التسجيل في المقرر",
"when enrolled — high school, or grade 8 if taking it early": "عند التسجيل — المرحلة الثانوية، أو الصف 8 إن أُخذ مبكرًا",
"ACT — state administration": "ACT — تنظّمه الولاية",
"grade 11": "الصف 11",
"ACT WorkKeys": "ACT WorkKeys",
"grade 11–12, career and technical pathways": "الصفان 11–12، المسارات المهنية والتقنية",
"MAAP-A (alternate assessment)": "MAAP-A (التقييم البديل)",
"IEP-team decision only · significant cognitive disability": "بقرار فريق IEP فقط · إعاقة معرفية شديدة",
"Notes for the District Test Coordinator": "ملاحظات لمنسّق الاختبارات في المنطقة",
"First-year EL and the ELA state test": "متعلّم السنة الأولى واختبار الولاية في الإنجليزية",
"Not applicable — not in first 12 months": "لا ينطبق — ليس في الأشهر الـ12 الأولى",
"DTC confirmed: takes ELA with accommodations": "أكّد المنسّق: يؤدي اختبار الإنجليزية مع تسهيلات",
"DTC confirmed: exempt from this year's ELA administration": "أكّد المنسّق: معفى من اختبار الإنجليزية هذا العام",
"Not yet confirmed with the DTC": "لم يُؤكَّد بعد مع المنسّق",
"Report card / progress report notes that the student receives EL supports and accommodations": "يُذكر في كشف الدرجات / تقرير التقدّم أن الطالب يتلقى دعم وتسهيلات EL",
"Parents told, in a language they understand, what accommodations are used and how grades are earned": "أُبلغ أولياء الأمور، بلغة يفهمونها، بالتسهيلات المستخدمة وكيفية احتساب الدرجات",
"Progress reports and report cards sent home translated or orally interpreted": "تُرسل تقارير التقدّم وكشوف الدرجات مترجمة أو مع ترجمة شفوية",
"Student is not retained solely because of English proficiency": "لا يُعاد الطالب في صفه بسبب مستوى الإنجليزية وحده",
"Promotion decisions consider ELPT growth and time in U.S. schools, not grade-level English alone": "تراعي قرارات الترفيع التقدّم في ELPT ومدة الدراسة في الولايات المتحدة، لا إنجليزية الصف وحدها",
"Retention is under consideration for this student": "يُنظر في إعادة هذا الطالب في صفه",
"Interventions documented showing English is not the barrier — plus the parent meeting date and the parents' signed agreement": "تدخّلات موثّقة تُظهر أن الإنجليزية ليست العائق — مع تاريخ اجتماع ولي الأمر وموافقته الموقّعة",
"Strategies / who": "الاستراتيجيات / مَن",
"— what is done, and by whom": "— ما الذي يُعمل ومَن يعمله",
"Evidence of progress": "دليل التقدّم",
"— instrument, how often, where kept, what counts": "— الأداة، التكرار، مكان الحفظ، ما يُحتسب",
"Status (MSIS)": "الحالة (MSIS)",
"Active EL": "متعلّم نشط",
"Active EL — parent declined services": "متعلّم نشط — رفض ولي الأمر الخدمات",
"Monitored Year 1": "تحت المتابعة السنة 1",
"Monitored Year 2": "تحت المتابعة السنة 2",
"Monitored Year 3": "تحت المتابعة السنة 3",
"Monitored Year 4": "تحت المتابعة السنة 4",
"Exit criterion": "معيار الخروج",
"Level 4 or higher in each ELPT domain, same administration": "المستوى 4 أو أعلى في كل مهارة من ELPT، في الجلسة نفسها",
"Plan written": "تاريخ كتابة الخطة",
"Reviewed after ELPT results": "روجعت بعد نتائج ELPT",
"Nine-weeks reviews": "مراجعات كل تسعة أسابيع",
"— grades, attendance, ELPT progress; teachers initial changes": "— الدرجات والحضور وتقدّم ELPT؛ يوقّع المعلمون بالأحرف الأولى على التغييرات",
"Q1 date · initials": "الربع 1 التاريخ · الأحرف الأولى",
"Q2 date · initials": "الربع 2 التاريخ · الأحرف الأولى",
"Q3 date · initials": "الربع 3 التاريخ · الأحرف الأولى",
"Q4 / end-of-year · initials": "الربع 4 / نهاية العام · الأحرف الأولى",
"Review notes / changes": "ملاحظات المراجعة / التغييرات",
"Teachers of record receiving this plan": "المعلمون الذين يتسلّمون هذه الخطة",
"Given to teachers on": "سُلِّمت للمعلمين بتاريخ",
"Copy to cumulative folder on": "نسخة إلى الملف التراكمي بتاريخ",
"Translated / interpreted for parent": "تُرجمت / فُسِّرت شفويًا لولي الأمر",
"Translated written copy given": "سُلِّمت نسخة مترجمة مكتوبة",
"Interpreted orally at the conference": "تُرجمت شفويًا في الاجتماع",
"Both — translated copy and interpretation": "كلاهما — نسخة مترجمة وترجمة شفوية",
"Not needed — parent reads English": "غير مطلوب — ولي الأمر يقرأ الإنجليزية",
"Not yet": "ليس بعد",
"· date": "· التاريخ",
"Lane:": "المسار:",
"Level": "المستوى",
"Testing accommodations": "تسهيلات الاختبار",
"for the District Test Coordinator · from the Language Service Plan": "لمنسّق الاختبارات في المنطقة · من خطة الخدمات اللغوية",
"District Test Coordinator · date": "منسّق الاختبارات في المنطقة · التاريخ",
"EL teacher · date": "معلّم EL · التاريخ",
"classroom — every teacher of record · chosen from each domain's level; gold edge = the builder's pick": "الصف — كل معلّمي الطالب · اختيرت حسب مستوى كل مهارة",
"one measurable goal each — suggest from the level, or choose from the ELPA21 goal bank (80 goals, each tied to an ELP Standard)": "هدف واحد قابل للقياس لكل مهارة",
"Content graded for accuracy; language errors not penalized on non-ELA work": "تُقيَّم صحة المحتوى؛ لا تُخصم أخطاء اللغة خارج مادة اللغة الإنجليزية",
"Newcomer": "قادم جديد",
"Challenge": "تحدٍّ",
"Identified in": "تم تحديده في",
"— Home Language Survey, screener and first notification are in the cumulative folder.": "— استبيان لغة المنزل واختبار الفرز والإشعار الأول محفوظة في الملف التراكمي.",
"Monitored former EL: no EL services. Classroom supports continue where a teacher sees a need; grades, attendance and assessments are checked every nine weeks (section 9). A student struggling for language reasons may re-enter with documented reasons and parent consent.": "متعلّم سابق تحت المتابعة: لا خدمات EL. يستمر الدعم في الصف حيث يرى المعلّم حاجة؛ تُراجَع الدرجات والحضور والاختبارات كل تسعة أسابيع (القسم 9). يمكن للطالب الذي يواجه صعوبة لأسباب لغوية أن يعود إلى البرنامج بأسباب موثّقة وموافقة ولي الأمر.",
"(monitored: four years after exit, checked every nine weeks; re-entry requires documented reasons and parent consent)": "(تحت المتابعة: أربع سنوات بعد الخروج، تُراجَع كل تسعة أسابيع؛ تتطلب العودة أسبابًا موثّقة وموافقة ولي الأمر)",
"Immigrant (Title III)": "مهاجر (Title III)",
"Long-term EL": "متعلّم طويل الأمد",
"_note": "نسخة للأسرة. العناوين والخيارات بالعربية؛ أما الأهداف والاستراتيجيات والأدلة والملاحظات فتظهر كما كتبها المعلّم بالإنجليزية وتُشرح بمساعدة مترجم شفوي. النسخة الإنجليزية هي السجل الرسمي.",
},
};
